export default {
  add: 'Add',
  remove: 'Remove',
  new: 'New',
  demo: 'Demo',
  get: 'Get',
  receive: 'Receive',
  check: 'Check',
  vote: 'Vote',
  show_more: 'Show more',
  read_more: 'Read More',
  show_less: 'Show less',
  no_records: 'No records found',
  no_favorites: 'No favorites found',
  no_data: 'No data',
  or: 'or',
  copy: 'Copy',
  close: 'Close',
  change: 'Change',
  submit: 'Submit',
  disable: 'Disable',
  enable: 'Enable',
  coming_soon: 'Coming soon',
  delete: 'Delete',
  send: 'Send',
  send_code: 'Send Code',
  other_news: 'Other news',
  all_news: 'All news',
  welcome: 'Welcome!',
  cancel: 'Cancel',
  back: 'Back',
  confirm: 'Confirm',
  next: 'Next',
  search: 'Search',
  ask_question: 'Ask a question',
  to_balance_page: 'To balance page',
  share: 'Share',
  join_us: 'Join us',
  published: 'Published',
  sent_modal: 'Sent',
  password_change: 'Password changed',
  enable_cookies_app: 'This feature does not work without cookies',
  value_not_found: 'Value not found',
  time: {
    day: 'day | days',
    hour: 'hour | hours',
    min: 'min',
    sec: 'sec',
  },
  fiat_widthrow: {
    order_canceled: 'Order canceled',
    success_link:
      'Order successfully created. Confirmation link has been sent to your email ',
    success_coin:
      'Withdraw confirmation link sent to your email. Please check and confirm',
    success_coin_2:
      'Two-factor authentication code has been sent to your email',
    success: 'Confirmation link has been sent to your email',
    error: 'Sorry this code is not valid',
    activated: 'Link successfully activated',
    err_activated: 'Sorry this code is not valid',
  },
  meta: {
    main_title: 'Cryptocurrency Exchange Platform | Coinzix',
    main_description:
      'Coinzix Cryptocurrency Exchange - Buy and sell bitcoins and altcoins on one of the most convenient and reliable crypto platforms.',
    markets_title: 'Crypto Currencies Price | Coinzix',
    markets_description:
      'Coinzix cryptocurrency market - The easiest way to know the last prices, coin market cap, and 24h change of bitcoin and other altcoins',
    trading_title: '{rate} | {pair} | Spot Trading | Coinzix',
    login_title: 'Log In | Coinzix',
    login_description:
      'Sign in using your email address and password to get access to your account. Logged in users can buy, sale and exchange crypto coins.',
    about_title: 'About us | Coinzix',
    about_description:
      'Find out more about Coinzix, a cryptocurrency exchange specialized in crypto trading and blockchain technology!',
    terms_and_conditions_title: 'Terms and Conditions | Coinzix',
    terms_and_conditions_description:
      'Read the terms and conditions of Coinzix Cryptocurrency Exchange, before you start trading.',
    privacy_policy_title: 'Privacy Policy | Coinzix',
    privacy_policy_description:
      'Read the privacy policy of Coinzix Cryptocurrency Exchange, before you start trading.',
    cookies_policy_title: 'Cookies Policy | Coinzix',
    cookies_policy_description:
      'We use cookies to personalize content and ads, provide social media features, and analyze our traffic. Read more about it here.',
    risk_disclosure_statement_title: 'Risk Disclosure Statemnt | Coinzix',
    risk_disclosure_statement_description:
      'Read our risk disclosure statement before you start trading, to ensure you are aware of the risks associated with crypto trading.',
    currencies_tokens_title: 'Currencies and Tokens | Coinzix',
    currencies_tokens_description:
      'See our complete list of crypto coins ranked by volume, 1inch, rate, market cap, 24-hour change, and many more.',
    fees_title: 'Fees and Commissions | Coinzix',
    fees_description:
      'Read more about fees and commissions when trading on the Coinzix Cryptocurrency Exchange platform.',
    pair_description:
      "Romania's leading crypto exchange. Fully regulated. Buy, sell, and trade a variety of crypto assets including {pair}!",
    status_online_title: 'Status Online | Coinzix',
    status_online_description:
      'See our complete list of crypto coins ranked by last successful transaction, average processing time or whether or not you can deposit or withdraw it online.',
    submit_request_title: 'Submit a Request | Coinzix',
    submit_request_description:
      'Reach out to us for any questions or requests you have in regards to Coinzix Cryptocurrency Exchange.',
    support_title: 'Support | Coinzix',
    support_description:
      'Our team of experts is available 24/7 to answer your questions and provide assistance with any issues you may have. Contact us today!',
  },
  margin: {
    transfer: 'Transfer',
    from: 'From',
    ex_wallet: 'Exchange Wallet',
    margin_wallet: 'Margin Wallet',
    to: 'To',
    coin: 'Coin',
    amount: 'Amount',
    available: 'Available',
    confirm_transfer: 'Confirm Transfer',
    active_position: 'Active Positions',
    positions_history: 'Positions History',
    funds: 'Funds',
    profit_rate: 'Profit rate',
    loss_rate: 'Loss Rate',
    notifiration_approve: 'Withdraw successfully confirmed',
    notifiration_canceled: 'Withdraw successfully canceled',
  },
  header: {
    nav: {
      free_coins: 'Free Coins',
      demo_trading: 'Demo Trading',
      social_listing: 'Social Listing',
      news: 'News',
      trade: 'Trade',
      spot_trading: 'Spot Trading',
      spot_exchange: 'Spot Exchange',
      wallet: 'Wallet',
      launchpad: 'Launchpad',
      account_dropdown: {
        account: 'Account',
        security: 'Security',
        verification: 'Verification',
        referral: 'Referral program',
        vip: 'VIP Level',
        api_management: 'API Management',
      },
      balance: 'Balance',
      support: 'Support',
      contacts: 'Contacts',
      fees: 'Fees',
      exchange: 'Exchange',
      markets: 'Markets',
      partner_news: 'Partner news',
      blog: 'Blog',
      margin: 'Margin',
      staking: 'Staking',
      buy_crypto: 'Buy Crypto',
      buy_crypto_card: 'Credit / Debit Card',
      buy_crypto_with_card: 'Buy crypto with card',
      buy_fiat_euro: 'Deposit Euro',
      buy_fiat_bank_euro: 'Deposit euro using bank transfer',
    },
    logbox: {
      log_in: 'Log In',
      or: 'or',
      log_out: 'Log Out',
      sign_in: 'Sign In',
      sign_up: 'Sign Up',
      sign_up_now: 'Start Registration',
      forgot: 'Forgot password',
      restore: 'Restore password',
      setNewPass: 'Set new password',
    },
  },
  mob_nav: {
    graph: 'Graph',
    menu: 'Menu',
  },
  subscribe: {
    success_subscribe: 'Success subscribe',
    success_unsubscribe: 'Success unsubscribe',
  },
  TwoFA: {
    active: '2 FA activated',
    not_active: '2 FA deactivated',
    google_TwoFA:
      '2 factor authorization is already enabled. Disable current variant first',
  },
  referal: {
    ref_link: 'Referral link copied',
  },
  feedback: {
    feedback_notify: 'Thank you for your feedback',
  },
  landing_page: {
    title_text_strong: 'BUY AND SELL CRYPTOCURRENCY',
    title_text_regular:
      'ONE OF THE MOST CONVENIENT AND RELIABLE CRYPTO PLATFORMS',
    title_text_sub: 'BETA VERSION',
    title_text_top_reg: 'Register Now',
    title_text_top_buy: 'Buy now',
    title_text_reg: 'REGISTER NOW WITH A FEW SIMPLE STEPS',
    proven_platform: 'Proven platform for profitable trading and investment',
    start_trading: 'Start trading cryptocurrency now',
    create_and_start: 'Create your account and start immediately',
    whole_list: 'Whole list',
    blocks: {
      link_analytics: 'Professional market analytics',
      link_x_platform: 'X-Platform to launch IEO',
      text_processing_speed:
        'Processing speed transactions and TCP connections',
      text_guaranteed: 'Premium security against hacker attacks',
      link_support_24: '24/7 Online Support',
      text_more_than: 'More than 90% of currencies in cold wallets',
      link_api: 'API Documentation',
      text_user_friendly:
        'User-friendly interface with all the tools you need ',
    },
  },
  auth_page: {
    email: 'Email',
    password: 'Password',
    oldPassword: 'Old password',
    passRepeat: 'Repeat password',
    userName: 'Username',
    createAccount: 'Create New Account',
    open_account: 'Open Account',
    confirm: 'Confirm',
    forgot_pass: 'Forgot password?',
    timezone: 'Timezone',
    agree_checkbox: {
      agree: 'I agree to the ',
      terms_of_use: 'Terms of Use',
      privacy_policy: 'Privacy Policy',
      and: 'and',
      ending: '',
      lang: '',
      confirmation_required: 'The confirmation field is required',
    },
    already_have: 'Already have and account?',
    forgot_password_title: 'Forgot password',
    resend_activation_title:
      'Your account is not activated yet. Please check your email.',
    resend_activation_text_1:
      'If you did not receive an email please check your spam folder or',
    resend_activation_button: 'click here',
    resend_activation_text_2: 'to resend it',
  },
  captcha: {
    click_to_verify: 'Click to verify',
    verification_success: 'Successful Verification',
  },
  faq: {
    registration: 'Registration and Login',
    registration1: '1. Registration and Login',
    general: 'General Introduction',
    list: 'The list of currencies',
    comission: 'Comission Information',
    data: 'The data safety',
    verification: 'Verification',
    functionality: 'Functionality of the site',
    confirm: '2. I didn`t get a confirmation link via email, what should I do?',
    reasons:
      'There are 4 possible reasons that can make such situation happen: 1. Your email client blocks our emails. 2. The email got into the spam folder. 3. Your mailbox is full and does not have the ability to accept new letters. 4. Your password does not meet the requirements of the system, so an email with a confirmation link was not sent. Please, contact our support team and we`ll help you to solve the problem',
  },
  withdraw: {
    popup:
      'Linkul de confirmare a fost trimis pe emailul tău. Te rugăm să verifici și să confirmi',
    error_address: 'Error get coin address',
  },
  profile: {
    title: 'Profile',
    account: {
      title: 'Account',
      email: 'Email',
      user_name: 'Username',
      language: 'Language',
      lang_en: 'English',
      lang_ro: 'Română',
      lang_ru: 'Русский',
      lang_ua: 'Українська',
      password: 'Password',
      time_zone: 'Timezone',
      notify_me: 'Notify me of any news, promotions or announcements by email',
      we_ensure:
        "We guarantee the safety storage and confidentiality of your data. If you have any additional questions, please don't hesitate to",
      contact_us: 'contact us',
      support: 'Support',
      address_book: {
        title: 'Address book',
        withdrawing_crypto:
          'Withdrawing cryptocurrencies from our platform, requires specifying a destination address. The address book intended for labeling and saving destination addresses for easy use later. When withdrawing, you can quickly and easy select an address from your address book.',
        table: {
          iso: 'ISO',
          iso_new: 'Currency',
          address: 'Address',
          label: 'Name',
          add_to_address_book: 'Add to Address book',
          currency: 'Currency',
          address_label: 'Name',
        },
      },
    },
    whitelist: {
      title: 'Withdrawal whitelist',
      whitelist: 'Whitelist',
      body_text:
        'Adding wallet addresses to the Address Book marked as "Withdrawal whitelist" ensures the protection of your funds by allowing withdrawals to these addresses only.',
      please_activate_2fa: 'Please activate 2FA.',
      please_activate_2fa_book:
        'To add your wallet address to whitelist, please enable 2FA.',
      add_to_white_list: 'Add to Whitelist',
      success_enable: 'Withdrawal whitelist has been successfully enabled',
      success_disable: 'Withdrawal whitelist has been successfully disabled',
      book_enable:
        'The wallet address has been successfully added to the WhiteList',
      book_disable:
        'The wallet address has been successfully removed from the WhiteList',
    },
    security: {
      title: 'Security',
      account_token: 'Account token (key):',
      please_consider:
        'Please consider our available options for increasing the security of your account. We want to ensure you that your account is secure with us.',
      do_not_share_codes:
        'Please do not divulge or share your password, Google Authentication Codes or Email to anyone, including Coinzix Support.',
      still_have_questions: 'Still have questions? Ask for ',
      email_authorization: 'Email authorization',
      each_time_you_login_email:
        'Everytime you login, a unique code will be send to your email',
      google_authorization: 'Google App Authorization',
      each_time_you_login_google:
        'Everytime you login, a new code from your Google App Authorization will be required',
      antifishing_code: 'Anti-phishing Code',
      antifishing_text1:
        'Please make sure that you use our available options for increasing the security of your account. Install an Anti-Phishing Code to distinguish genuine Coinzix notifications and emails from various phishing attempts.',
      device_management: 'Device Management',
      device: 'Device',
      date: 'Date',
      location: 'Location',
      ip_address: 'IP Address',
    },
    vip: {
      title: 'VIP Level',
      label: 'new',
    },
    verification: {
      title: 'Verification',
      to_deposit_or_withdraw:
        'To deposit or withdraw US dollars or other fiat currencies, your account details must be verified in order to comply with all relevant laws and requirements regulators to combat money laundering and terrorist financing.',
      has_developed:
        'has developed an online verification process, where an online application form is required to be filled and attach accompanying documents. In addition, you will also need to download, sign and send a declaration confirming the correctness of this information and',
      projects_permission: '`s permission to verify it.',
      choose_type: 'Select type',
      project_offers:
        'offers two account types. To continue, please select one option',
      please_note: 'Please note',
      all_documents:
        'All documents provided must be in Roman/Latin alphabet or a certified English translation is required.',
      all_files: 'All files uploaded must be in pdf, jpg or jpeg.',
      all_fields:
        'All fields in the following verification form are mandatory (NA for Non Applicable can be used).',
      to_avoid:
        'To avoid possible delays, please make sure that you check the documents correctness before submitting. Please double check you do not send the same document twice and possibly forget one.',
      here_you_can_track:
        'Here you can track the verification process. Please complete all the sections below. As soon as all the sections are completed and the documents are provided, our team of auditors will begin to check all the required information and confirm your account.',
      still_have_questions: 'Still have questions? Ask for',
      you_may_reset: 'You may reset your account type',
      reset: 'Reset',
      avg_time_complete:
        'The average time of completing your request is about 1 hour, but processing may take longer, up to 24 hours.',

      form: {
        name: 'Name',
        submitted: 'Submitted',
        approved: 'Approved',
        information_for:
          'Information for a genuine identification of the account holder',
        to_change: 'To change the already configured credentials, please visit',
        begin: 'Begin',
        address: 'Address',
        location_info: 'Location information for reliable metering.',
        manage_documents: 'Manage documents',
        view_existing:
          'View existing documents and add new ones. Convenient to download any additional requested files or replace obsolete documents.',
        enter_name_first: 'Enter your name as first required step',
        first_name: 'First name',
        last_name: 'Last name',
        middle_name: 'Middle name',
        gender: 'Gender',
        female: 'Female',
        male: 'Male',
        enter_address: 'Enter your address',
        country_state: 'Country / State',
        city: 'City',
        street: 'Street',
        post_code: 'Post Code',
        select_document: 'Select the document and its type',
        select_file: 'Select a file...',
        please_select_file_err: 'Please select a file',
        please_choose_type_err: 'Please choose the document type',
        size_error: 'File exceeds max size',
        format_error: 'This file format is not supported',
        choose_doc_type: 'Choose document type',
        please_formats:
          'Please upload the file in one of the following supported formats: PDF, PNG, JPEG. Max file size is 5Mb.',
        uploaded_docs: 'Uploaded documents',
        upload_time: 'Upload time',
        status: 'Status',
        type: 'Type',
        doc_on_moderation: 'On moderation',
        doc_approved: 'Approved',
        doc_canceled: 'Canceled',
        doc_declined: 'Declined',
        doc_passport: 'Passport',
        doc_drivers_lic: "Driver's license",
        doc_id_card: 'ID card',
        doc_bank_statement: 'Bank statement',
        doc_util_bills: 'Utility bills',
      },
      individual_account: {
        title: 'Individual account',
        account_on_behalf: 'account on behalf of an individual',
        verification_requirements: 'Verification Requirements',
        complete_form: 'Complete the online form.',
        age: 'Age: at least 18 years old.',
        information:
          'Information: telephone number, email address and residential address.',
        identification:
          'Identification: two forms of a valid government issued identification with picture; i.e., passport, national ID card, driving license, residency card, employment permit card, etc.',
      },
      corporate_account: {
        title: 'Corporate account',
        account_on_behalf:
          'account on behalf of a corporation, company, partnership or foundation',
        verification_requirements: 'Verification Requirements',
        complete_form: 'Complete the online form',
        corporate_documents: 'Corporate Documents',
        director_information:
          'Director Information: each director, significant shareholder and controlling officer(s) are required to provide identification. Please review the online form to find our more.',
        after_completing:
          'After completing the corporate verification form, an individual form for each director of your organization, significant shareholder(s) and controlling officer(s) will be required to be completed.',
      },
      referral_title: 'Referral program',
    },
    referral: {
      get_link: 'Get your link',
      reg_and_copy: 'Register and copy referral link',
      inv_friends: 'Invite your friends',
      inv_friends_to_reg:
        'Invite your friends to register using the referral link and get rewards once they complete a trade',
      get_rewards: 'Get rewards',
      receive_up_to: 'Receive up to {data}% commission in real time',
      about_program: 'About Program',
      ref_link: 'Referral link',
      support_level:
        'support {levels} level referral system. Each level has its own % which is equal to {first}% for 1st',
      support_level_2: ', {percent}% for 2nd',
      support_level_3: ' and {percent}% for 3d level',
      all_ref_data: 'All referral program data',
      my_refs: 'My referrals',
      total_earnings: 'Total earnings',
      refs_with_rate: 'Referrals with rate',
      email: 'Email',
      earnings: 'Earnings',
      reg_date: 'Date of registration',
      count: 'Count',
      ref_rate: 'Rate',
      level: 'Level',
      oops: 'Oops, looks like you are already logged in',
    },
    api_management: {
      title: 'API Management',
      label: 'new',
      save: 'Save',
      cancel: 'Cancel',
      input_label: 'Name API key to proceed',
      input_required_error: 'Please enter API key label',
      submit_button: 'Create API',
      api_info: {
        1: 'Each account can create up to 10 API Keys.',
        2: 'Do not disclose your API Key to anyone to avoid asset losses. It is recommended to bind IP for API Key to increase account security.',
        3: 'Be aware that your API Key may be disclosed by authorizing it to a third-party platform.',
        4: 'Please perform KYC before creating API. ',
      },
      subtitle: 'API List',
      delete_all: 'Delete all API',
      locked: 'Locked',
      edit: 'Edit restrictions',
      delete: 'Delete',
      qr: 'Scan to get address',
      key_label: 'API Key',
      secret_key_label: 'Secret Key',
      restriction_label: 'API restrictions',
      ip_access_label: 'IP Access restrictions',
      restriction: {
        read: 'Read',
        spot: 'Enable spot trading',
        withdrawal: 'Enable withdrawal',
      },
      ip_access: {
        all: 'Unrestricted (Less Secure)',
        trusted: 'Restrict access to trusted Ips only (Recomended)',
      },
      ip_access_trusted_placeholder:
        'When entering more than one IP address, please separate them width spaces',
      ip_access_trusted_required: 'Please enter trusted IP addresses',
      ip_access_trusted_incorrect:
        'Please enter correct trusted IP addresses separated with space',
      modal: {
        title: 'Security verification',
        verification_email: 'E-mail verification code',
        verification_email_required: 'E-mail verification code is required',
        twofa_email: 'Email 2fa code',
        twofa_email_required: 'Email 2fa code is required',
        twofa_google: 'Google 2fa code',
        twofa_google_required: 'Google 2fa code is required',
        code_incorrect: 'Incorrect code',
      },
      notifications: {
        create: 'Api created',
        delete: 'Api deleted',
        update: 'Api updated',
        add_deleted: "All Api's deleted",
      },
    },
  },
  landing_table: {
    search_coin_name: 'Search Coin Name',
    favorites: 'Favorites',
    all: 'All',
    markets: 'Markets',
    markets_last: 'Markets',
    pair: 'Pair',
    change: 'Change',
    coin: 'Coin',
    last_price: 'Last Price',
    high_24: '24h High',
    low_24: '24h Low',
    h_24: '24h',
    volume: 'Volume',
    tickers: 'Tickers',
    vol: 'VOL',
    trade: 'Trade',
    show_more: 'Show more',
  },
  twofactor: {
    activ: '2 FA activated',
    deactiv: '2 FA deactivated',
  },
  fiat_info: {
    incorrect: 'Incorrect code',
    require: 'Field Amount is required',
    zero_amount: 'Value must be greater than 0',
    err: 'Field Beneficiary Reference is required',
    err_max_length: 'Field Beneficiary Reference max length is ',
    fee: 'Withdraw fee',
    ben_err_acc: 'Field Beneficiary Account is required',
    ben_err_acc_max_length: 'Field Beneficiary Account max length is ',
    comment: 'Comment',
    bank_name: 'Bank name',
    ben_err: 'Field Beneficiary Name is required',
    ben_err_max_length: 'Field Beneficiary Name max length is ',
    bank_err: 'Field Bank Name is required',
    bank_err_max_length: 'Field Bank Name max length is ',
    ben_name: 'Beneficiary name',
    ben_acc: 'Beneficiary account',
    balance: 'Account Balance',
    reserved: 'reserved',
    turnover: 'This Mounth Turnover',
    outbound: 'Outbound',
    inbound: 'Inbound',
    send: 'Send',
    ben_ref: 'Beneficiary reference',
    deposit_limit: 'Exceeding limits on fiat deposits',
    withdraw_limit: 'Exceeding fiat withdrawal limits',
  },
  fiat_refill_info: {
    amount_required: 'Field amount is required',
    amount_min_value: 'Min refill is',
  },
  verify: {
    status: 'Status verification',
    level: 'Level',
    level_0: 'Level 0',
    level_1: 'Level 1',
    level_2: 'Level 2',
    complete: 'Verified',
    in_process: 'Start the verification',
    not_verified: 'Not verified',
    l_deposit: 'Crypto deposit: unlimited',
    l_withdraw: 'Crypto withdraw: {amount} {currency}/day',
    l_fiat: 'Fiat withdraw and deposit: ',
    l_fiat_locked: 'locked',
    l_fiat_money: '/month',
  },
  landing_inputs: {
    email_placeholder: 'Enter email',
    demo: 'Trade Now',
  },
  status_online_page: {
    status_online: 'Status Online',
    table: {
      coin: 'Coin',
      trading: 'Trading',
      deposits: 'Deposits',
      withdrawals: 'Withdrawals',
      pending: 'Pending confirmations',
      last_trade: 'Last successful trade',
      avg_time: 'Avg. processing time',
      online: 'Online',
      offline: 'Offline',
      d: 'd.',
      hr: 'hr.',
      min: 'min.',
      sec: 'sec.',
    },
  },
  trade_fees: {
    trade_fees_info: 'Trading fees information',
    trade_fees_info_cut: 'Trading fees',
    table: {
      pair: 'Pair',
      market: 'Market',
      limit: 'Limit',
    },
  },
  staking: {
    suc_change: 'Success change Accrued',
    profit: 'Take profit success',
    staking_alert: 'The amount staking field is required',
    error_staking: {
      balance: 'Not enough available balance',
      zero_input: 'The amount staking field is required',
      start_staking: 'Staking success',
      stop_staking: 'Success stop invest',
    },
    staking_plans: {
      daily: 'Daily',
      weekly: 'Weekly',
      monthly: 'Monthly',
      start_staking: 'Start Staking',
      active_staking: 'Redeem Reward',
    },
    modals: {
      accrued_reward_modal: {
        confirm_disabling: ' Confirm Disabling',
        confirm_enabling: 'Confirm Enabling',
        accrued_reward: 'Accrued Reward',
        confirm: 'Confirm',
        cancel: 'Cancel',
      },
      confirm_staking_modal: {
        confirm_staking: 'Confirm Staking?',
        coin_name: 'Coin Name',
        staking_amount: 'Staking amount',
        period: 'Period',
        estimated_annual_yield: 'Estimated Daily Yield',
        accrued_reward: 'Accrued Reward',
        cancel: 'Cancel',
      },
      redeem_reward_modal: {
        redeem_reward: 'REDEEM REWARD',
        confirm_reward: 'CONFIRM TO REDEEM YOUR REWARD?',
        redeemable_amount: 'Redeemable amount:',
        yes: 'Yes',
        no: 'No',
      },
      star_staking_modal: {
        start_staking: 'START STAKING',
        enter_staking: 'Enter the Staking amount for',
        total_amount: 'Total amount available for Staking:',
        accrued_yield: 'Accrued yield:',
        staking: 'Start Staking',
        buy: 'Buy',
        deposit: 'Deposit',
      },
      stop_staking_modal: {
        stop: 'Stop',
        stop_current_staking:
          'Do you really want to stop the current Staking plan?',
        balance_locked:
          'Once the current Staking plan is stopped all the balance locked in Staking together with the accumulated Reward will be credited to your Total balance on Coinzix exchange.',
        stop_plan: 'Stop current staking plan',
        cancel: 'Cancel',
      },
    },
    tabs: {
      history_tab: {
        date: 'Data',
        event: 'Eveniment',
        plan_ID: 'Plan/ID',
        reward_change: 'Reward Change',
        plan_before: 'Plan Amount Before',
        plan_after: 'Plan Amount After',
        balance_change: 'Available Balance Change',
        balance_before: 'Available Balance Before',
        balance_after: 'Available Balance After',
        not_modifiend: 'Not modified',
        no_data: 'No data',
      },
      my_active_plans_tab: {
        asset: 'Asset',
        annual_yield: 'Estimated Daily Yield',
        period: 'Period',
        amount: 'Amount',
        generated_reward: 'Generated Reward',
        accrued_reward: 'Accrued Reward',
        daily: 'Daily',
        monthly: 'Monthly',
        redeem_reward: 'Redeem Reward',
        stop: 'Stop',
        no_data: 'No data',
      },
      staking_plans_tab: {
        asset: 'Asset',
        annual_yield: 'Estimated Daily Yield',
        period: 'Period',
        min_amount: 'Min Amount',
        daily: 'Daily',
        monthly: 'Monthly',
        weekly: 'Weekly',
        start_staking: 'Start Staking',
        no_data: 'No data',
      },
    },
    staking: {
      plans: 'Staking Plans',
      rewards: 'Earn rewards for holding coins and tokens',
      staking_plans: 'Staking plans',
      my_active: 'My Active Plans',
      my_history: 'My Staking History',
    },
    event: {
      invest: 'Transfer to staking',
      payment: 'Payment',
      take_profit: 'Take profit',
      closed: 'Closed',
    },
  },
  staking_old: {
    minting_rewards: {
      my_rewards: {
        previous_rewards: 'Previous Rewards',
      },
    },
  },
  coins_fees: {
    with_and_dep_fees: 'Withdraw And Deposit Fees',
    table: {
      coin: 'Coin',
      refill_commissions: 'Refill commissions',
      withdraw_commissions: 'Withdraw commissions',
      coin_type: 'Coin type',
      percent: 'Percent',
      fixed: 'Fixed',
      minimal: 'Minimal',
      free: 'FREE',
    },
    formula_text:
      '* Commission is calculated by the formula: Fee = Percent of withdrawal amount + Fixed; if Fee is less than the Minimal then the Minimal is charged.',
  },
  cur_tokens: {
    title: 'Currencies & Tokens',
    table: {
      coin: 'Coin',
      token_type: 'Type',
      rate: 'Rate',
      market_cap: 'Market cap',
      change_24: '24 hour change',
      volume_24: '24 hour volume',
      n_a: 'N/A',
    },
  },
  free_coins: {
    title: 'BONUS COINS',
    special_offer: 'The daily limits have been doubled.',
    special_wishes: 'Happy New Year and Merry Christmas!',
    project_faucets:
      'We have something we know you would like. Redeem now your free cryptocurrency coins and become a member of the exclusive club of Coinzix Loyal Users. Find more details below. Stay tuned on our Community channels for the latest news.',
    click_get: 'COLLECT YOUR FREE COINS below:',
    history: 'History',
    rules: {
      title: 'Information',
      general_description: {
        title: 'Coinzix Loyal Users Club',
        desc_1:
          'A list of various coins is offered for free to our Coinzix Loyal Users Club members.',
        desc_2:
          'The coins are updated regularly based on our users’ preferences.',
        desc_3:
          'Every cryptocurrency has a limit per session, that is marked in the table above.',
        desc_4:
          'Every session has a pre-defined duration within you can  receive the specified number of coins, marked as well in the table above.',
        desc_5: 'The bonus coins are offered only once per session.',
      },
      how_it_works: {
        title: 'How to redeem your Loyal User free coins?',
        desc_1: 'Log in or register on Coinzix Exchange Platform on our ',
        desc_1_link: 'Sign-Up page.',
        desc_2:
          'Select from the table above the currency you want to receive for free by clicking the button <Receive>.',
        desc_2_a:
          '<Note:> If the button is not active, either the daily volume of the coin has been shared already with our loyal users, either you have already received the available amount of the coin, but the sessions has not expired yet.',
        desc_2_b:
          '<Tip:> Check again the coin in few hours or after the “Time left” until the next refresh has passed, to unlock your new loyalty bonus.',
        desc_2_c:
          '<Coming soon:> We are loyal to you too! We are working hard to launch a functionality that will send automatic updates when a free coin is available again for collection.',
        desc_3: 'Click the “Get” button to collect your free coins.',
        desc_3_a:
          '<Note:> A separate window will appear with instructions on how to tell your friends from social media about your loyalty bonus. Post the link in your social media and share it with your friends. After your post, copy the link from the publication in the box, so our moderators can check it. The coins will be sent to your wallet after our team is validating the post.',
        desc_3_b:
          '<Tip:> Check again the coin in few hours or after the “Time left” until the next refresh has passed, to unlock your new loyalty bonus. ',
        desc_3_c:
          '<Important:> Do not delete the post after you receive the coins in your wallet, otherwise you will be banned from the loyalty program. ',
        desc_4: 'Coins are all yours now. Happy trading on our platform!',
      },
      summary: {
        desc_1:
          'We value our loyal users and care greatly about our amazing community!',
        desc_2:
          'Enjoy the time on our platform, meet our community and as a thank you from our side, collect the bonus free coins with only few clicks.',
        desc_3:
          'We make crypto easy and accessible for everyone, so come and visit our Community Channels for more news and opportunities.',
      },
    },
    table: {
      coin: 'Currency',
      socials: 'Social networks',
      payout_per_user: 'Payout per user',
      time_interval: 'Interval',
      daily_limit: 'Volume daily coins',
      time_left: 'Time left',
      date_time: 'Time',
      nickname: 'User',
      sum: 'Amount',
      payout: 'payout',
      limit: 'limit',
    },
    modal: {
      title: 'Get coins',
      to_get:
        'To get free coins please share the post about {project} exchange',
      please_insert: 'Please insert the link where we can check it',
      confirm_captcha: 'Please confirm captcha',
    },
    reject_modal: {
      top_lvl: 'Free Coins is temporarily blocked',
      second_lvl: 'and will be available through',
    },
  },
  voting: {
    title: 'Currency voting',
    round: 'Round',
    each_participant:
      'Each participant could select the candidates for whom he would like to vote below. Each registered user could vote for more than 1 candidate and could cast his full vote only once. There is no fee required.',
    min_number: 'Min number of votes for the current round is',
    next_round_starts_at: 'Next round starts at',
    day: 'day',
    of: 'of',
    starts_in: 'starts in',
    stats_is_hidden: 'Some statistics information are hidden. To show all',
    voting: 'Voting',
    history: 'History',
    information: 'Information',
    voting_time: 'Voting time',
    from: 'from',
    to: 'to',
    all_members: 'All members with a',
    account_are_eligible: 'account are eligible to participate in the vote',
    each: 'Each',
    user_can_vote: 'user can vote for as many candidates as he or she likes.',
    there_is_no_fee: 'There is no fee for voting.',
    please_note: 'Please note',
    will_review:
      'will review the final count of votes made by each candidate when the voting time period ends.',
    reserves_the_right:
      'reserves the right to adjust the way we assign value to each vote.',
    upon_completion:
      'Upon completion of the voting process and also the selection of a new coin for listing,',
    will_list_the_coin:
      'will list the coin on our exchange within a reasonable time frame. Based on market response and trading activity, we will try to conduct this event on a monthly basis.',
    project_reserves_all_rights:
      'reserves all rights to change the rules of the voting event without prior notification at any time, including revoking results or disqualifying candidates who are confirmed to have engaged in vote manipulation. This includes but is not limited to any form of financial or monetary incentives, airdrops or competition rewards offered that will influence user votes. The weight of each vote could also vary based on a list of factors including but not limited to the level of historical activity of the account used to vote and any other additional factors that we consider important.',
    all_past_voting_completed: 'All past voting rounds are completed',
    dont_miss: "Don't miss the upcoming rounds, follow",
    number_of_rounds: 'Number of rounds',
    status: 'Status',
    completed: 'Completed',
    winners: 'Winners',
    to_the_voting_page: 'To the voting page',
    coin_community_voting_results: 'Coin Community Voting Results',
    voting_results: 'Voting Results',
    results: 'results',
    per_round_capitalize: 'Per round',
    total_capitalize: 'Total',
    table: {
      no: 'NO.',
      coin: 'Coin',
      name: 'Name',
      number: 'Number',
      of_votes: 'of votes',
      proportion: 'Proportion',
      per_round_caps: 'PER ROUND',
      total: 'TOTAL',
      team: 'Team',
      whitepaper: 'Whitepaper',
      social: 'Social',
    },
  },
  downloads: {
    keep_in_touch:
      'Keep in touch while making deals and also receiving instant notifications',
    download_suitable_version:
      'Download the suitable version for you and register on the website.',
    smart_functional: 'Smart functional',
    trading: 'Trading',
    exchange_trading: 'Exchange trading, regulation of orders and positions',
    wallets: 'Wallets',
    transactions_between:
      'Transactions between the wallets and checking the latest account movements',
    login: 'Login',
    secured_api: 'Secured API keys access and PIN/password security',
    settings: 'Settings',
    graphic_interface: 'User interface configuration',
    notifications: 'Notifications',
    notifications_about:
      'Notifications about any conducted transactions or prices',
    popup: {
      trade_with: 'Trade with',
      mobile_app: 'mobile app',
      get: 'Get',
    },
  },
  trading: {
    cross: 'Cross',
    loss: 'Loss rate',
    profit: 'Profit rate',
    buy: 'Buy',
    sell: 'Sell',
    total: 'Total',
    price: 'Price',
    amount: 'Amount',
    sum: 'Sum',
    quantity: 'Quantity',
    available: 'Available',
    available_short: 'Avbl',
    open: 'Open',
    order: 'order',
    orders: 'orders',
    history: 'history',
    date: 'date',
    limit_order: 'Limit order',
    limit: 'Limit',
    market: 'Market',
    instant: 'Instant',
    advanced: 'Advanced',
    instant_exchange: 'Instant exchange',
    fast_easy: 'fast & easy',
    balance_available: 'Balance Available',
    instant_info: 'Please confirm conversation within the time.',
    you_receive: 'You will receive',
    you_pay: 'You will pay',
    preview_conversion: 'Preview Conversion',
    convert: 'Convert',
    please_new_quote: 'Quote expired. Please request a new quote.',
    new_quote: 'New Quote',
    ins_balance: 'Insufficient balance',
    ins_balance_min: 'Minimum amount is {amount}',
    ins_rate: 'There are currently no counterparty orders',
    ins_balance_to_max: 'Max.',
    stop_limit: 'Stop-Limit',
    open_orders: 'Open orders',
    order_history: 'Order history',
    order_id: 'Order ID',
    limit_price: 'Limit price',
    symbol: 'Symbol',
    type: 'Type',
    trade_type: 'Trade Type',
    volume_done: 'Volume Done',
    rate: 'Rate',
    status: 'Status',
    create_date: 'Create Date',
    sell_limit: 'Sell limit',
    fee: 'Fee',
    cancel: 'Cancel',
    more: 'More',
    market_trades: 'Market trades',
    time: 'Time',
    high: 'High',
    low: 'Low',
    market_price: 'Market price',
    stop: 'Stop',
    chart: 'Chart',
    no_trades: 'No trades',
    no_orders: 'No orders',
    order_processing: 'Order is sent for processing',
    order_completed: 'Order completed',
    profit_loss_zero: 'Value must be greater than 0',
    exchange_fee:
      'The fees associated with the usage of the instant exchange service are dynamic and automatically calculated by the system. Minimum fee 0,5% - 2,5% Maximum fee',
    commission: 'Commission',
    ticker: {
      coin: 'Coin',
      last_price: 'Last price',
      change: 'Change',
      volume: 'Volume',
    },
    tooltip: {
      total:
        'Note: This approximate amount that will be visible is a snapshot at the time of the calculation, based on the order book prices. If the price goes up/down by the time the user is submitting the order, it’s possible that the final amount the user sells/buys will differ.',
    },
    error: {
      rate_diff:
        'Unable to place the order. Selling balance is currently unavailable for the corresponding amount due to the rapid decline in prices. Try again by reducing the Total, or use Amount instead of Total.',
    },
  },
  orders: {
    type: {
      buy: 'Buy',
      sell: 'Sell',
    },
    trade_type: {
      limit: 'Limit',
      market: 'Market',
      stop_limit: 'Stop-Limit',
      instant: 'Instant',
    },
    status: {
      public: 'Public',
      done: 'Done',
      closed: 'Closed',
      in_process: 'In processing',
      creating: 'Creating',
    },
  },
  balance: {
    refill: 'Refill fee',
    title: 'Balance',
    est_value: 'Estimated Value',
    history: 'History',
    order_history: 'Order history',
    hide_small: 'Hide zero balances',
    all_history: 'All',
    deposit_history: 'Deposit',
    withdraw_history: 'Withdraw',
    history_order_history: 'Orders',
    go_to_exchange: 'Go to Exchange',
    table: {
      recent: 'Recent',
      time: 'Time',
      coin: 'Coin',
      type: 'Type',
      status: 'Status',
      available: 'Available',
      on_orders: 'On Orders',
      valuation: 'Valuation',
      lock_position: 'Lock Position',
      action: 'Action',
      all: 'All',
      deposit: 'Deposit',
      withdraw: 'Withdraw',
      cancel: 'Cancel',
      details: 'Details',
      address: 'Address',
      IBAN: 'IBAN',
      bank_name: 'Bank name',
      bank_address: 'Bank address',
      payment_comment: 'Comment',
      client_name: 'Client name',
      fee: 'Fee',
      memo: 'MEMO (TAG)',
      twofa_approve: '2FA Approve',
      captcha_approve: 'Captcha',
      email_confirmation: 'Email Confirmation',
      processing_time: 'Processing Time',
      id: 'Id',
      payment: 'Payment',
      dispatch_volume: 'Dispatch volume',
    },
    deposit: {
      contractAddress:
        "Token's name is {ISO_NAME} ({Full_Name}). Please make sure to deposit {ISO_NAME} ({Full_Name}) tokens under the contract address ending in {contractAddressEnd}.",
      deposit_address: 'Deposit Address',
      copy: 'Copy',
      qr_code: 'QR Code',
      view: 'View',
      deposit_history: 'Deposit History',
      to_track: 'to track status',
      cashier: 'Cashier',
      tips: {
        title: 'Tips',
        please_dont:
          "Please make sure that you don't deposit any other digital assets except {depositCoin} to the above address.",
        minimum_deposit:
          'Minimum deposit amount: {minRefillAmount} {depositCoin}. Any deposits less than the minimum, will not be credited or refunded.',
        refill_comission_deposit: 'Refill commission:',
        refill_comission_deposit_free: 'Free',
        depositing_to_above:
          'Depositing to the above address requires confirmations of the entire network. It will be accomplished after {confirmationsCount} confirmations.',
      },
      attention:
        'Warning! Select the type of {iso} token before making a deposit.',
      simpleAttention: 'Warning! The type of {iso} token is:',
      token_type: 'Token Type',
    },
    withdraw: {
      address: 'Address',
      amount: 'Amount',
      available: 'Available',
      min: 'Min',
      limit: 'Limit',
      fee: 'Fee',
      dispatch_volume: 'Dispatch volume',
      receive_amount: 'Receive amount',
      fee_from_amount: 'Fee from amount',
      request_withdraw: 'Request withdraw',
      range: 'Range',
      confirmations: 'Confirmations',
      tips: {
        title: 'Tips',
        to_ensure:
          'To ensure the safety of your funds, your withdrawal request will be manually reviewed if your security strategy or password is changed. Please expect for any phone calls or emails from our staff.',
        please_make_sure:
          'Please make sure that your computer and your browser are secured and your information is protected from being tampered or leaked.',
      },
    },
    crypto_statuses: {
      created: 'Created',
      sent: 'Sent',
      wait: 'Wait',
      moderation: 'Moderation',
      in_processing: 'In processing',
      wait_confirmations: 'Wait confirmations',
      deleted: 'Deleted',
      canceled: 'Canceled',
      emailed: 'Emailed',
      waiting_2fa_approve: 'Waiting 2fa approve',
      waiting: 'Waiting',
    },
    fiat_statuses: {
      created: 'Created',
      wait_pay: 'Wait pay',
      deleted: 'Deleted',
      canceled: 'Canceled',
      emailed: 'Emailed',
      done: 'Done',
      waiting_2fa_approve: 'Waiting 2fa approve',
      moderation: 'Moderation',
      in_process: 'In process',
      pending: 'Pending',
      wait_check: "Wait check user's data",
    },
    crypto_types: {
      refill: 'Refill',
      withdraw: 'Withdraw',
    },
    fiat: {
      refill_details: 'Order information',
    },
  },
  submit_request: {
    title: 'Support contact form',
    here_to_help: 'Here to assist you',
    title_head: 'Support',
    title_form: 'Support Form',
    type_message:
      'Type your message and describe the problem in details for a better and faster answer.',
    our_team_will_reply:
      'Our support team will reply you within about 24 hours.',
    your_email: 'Your email',
    choose_theme: 'Select theme',
    enter_message: 'Enter your message',
    themes: {
      account: 'Account',
      deposit: 'Deposit',
      security: 'Security',
      trading_common: 'Trading',
      withdraw: 'Withdraw',
      other: 'Other',
    },
  },
  ieo: {
    title: '{data} Launchpad',
    descr: 'Token launch platform',
    apply_btn: 'Apply To Launch',
    buy_coin_btn: 'Buy coin',
    round: 'Round',
    tokens_amount: 'Tokens Amount',
    available_curr: 'Available Currencies',
    air_drop: 'Air Drop',
    start_time: 'Start Time',
    end_time: 'End Time',
    minBuy: 'Min Buy Amount',
    price: 'Token Price',
    totalSell: 'Total Token Sell',
    myTokens: 'My Tokens',
    web_site: 'Website',
    balance: 'Balance',
    error: {
      no_rate: 'no rate data for this currency',
      max_amount: 'Max amount is',
    },
    filter: {
      all: 'All Projects',
      active: 'Active Projects',
      success: 'Success Projects',
      upcoming: 'Upcoming Projects',
    },
    info_statuses: {
      active: 'Active',
      upcoming: 'Upcoming',
      success: 'Success',
    },
    detail: {
      toPrepare: 'TO PARTICIPATE IN LAUNCHPAD',
      pleaseVerify: 'Please, login to your account',
      verify: 'Login',
      totalFunds: 'Total funds raised',
      timeLeft: 'Time left',
      about: 'About Project',
      doc: 'Documentations',
      tokenName: 'Token name',
      tokenPrice: 'Token Price',
      tokenType: 'Token Type',
      minPurchase: 'Minimum Purchase',
      distribution: 'Token`s distribution',
      timeCreate: 'Time Create',
      tokenAmount: 'Token`s Amount',
      bonus: 'Bonus',
      paymentCurr: 'Payment currency',
      status: 'Status',
      token_sale: 'Token Sale and Economics:',
      token_supply: 'Total token supply:',
      token_distribution: 'Token`s Distribution:',
      soft_cap: 'Soft cap',
      hard_cap: 'Hard cap',
      launchpad_allocation: 'Launchpad Allocation',
    },
  },
  notification: {
    error: {
      already_logged: 'You have been already logged in',
      email_already_taken: 'Sorry, this email has already been used',
      username_already_taken: 'Sorry, this username has already been used',
      invalid_code: 'Sorry, this code is not valid',
      file_not_selected: 'Upload file field is required',
      file_size_error: 'File exceeds max size',
      not_add_to_book: 'Address is not added to Address Book',
      incorrect_rate: 'The rate cannot be less then 0',
      incorrect_vol: 'Volume cannot be less then 0',
      incorrect_vol_then: 'Volume cannot be less then {data}',
      check_rate: 'Check if Rate is set',
      check_input:
        'Check inputs to have numbers, dots and to be between min-max values',
      err_create_order: 'Sorry, order cannot be created',
      err_create_order_27: 'Rights to this action are limited',
      some_err: 'Unexpected error',
      withdraw_not_create: 'Withdraw request cannot be created',
      withdraw_address: 'Address should contain at least 3 characters',
      not_enough: 'Not enough available balance',
      not_enough_on_balance: 'Not enough on balance ',
      not_enough_on_balance_iso: 'Not enough on balance {data}',
      check_inputs:
        'Check inputs to have numbers, dots and to be between min-max values',
      no_address: 'No address to show',
      no_payment_system: 'No payment system',
      not_get_email: 'We cannot get your email, please enter it',
      unknown_error: 'Error occurred',
      username_in_pass: 'Field Password cannot contain username',
      verify_docs_file_format:
        'This file format is not supported. Use one of these: pdf, jpeg, png, jpg',
      withdraw_sum_and_comm_amount:
        'Withdrawal sum and commission must be bigger than the minimal withdraw amount',
      withdraw_min_value: 'Min value is',
      withdraw_max_value: 'The Amount can not be greater than',
      withdraw_zero_amount: 'Amount must be greater than 0',
      no_server_response: 'No response from server, try again later',
      bad_server_response: 'No server connection',
      error_sending_pin_code: 'Error sending pin code',
      limit_receiving:
        'Limit receiving pin code has been exceeded. Please wait for sending up to 10 seconds',
      limit_receiving_activation:
        'Limit receiving activation email has been exceeded. Please wait for sending up to 2 minutes',
      error_sending: 'Error sending pin code via email',
      username_or_email: 'Provide another username or email',
      url: 'Link is not a valid',
      account_not_active: 'Account is not active',
      attempt_exceeded: 'Attempt limit exceeded',
      login_cred_error: 'Email or password is incorrect',
      withdraw_verif_error: 'Exceeding crypto withdrawal limits',
      refill_verif_error:
        'The verification process is required to be able to deposit',
      withdraw_create_error: 'Withdraw request is not created',
      withdraw_whitelist_error: 'Withdraw suspended',
      no_recieve_amount: 'The withdrawal amount must exceed the fee value',
      something_went_wrong: 'Something went wrong',
      upload_file_limit:
        'Unable to upload the file. Maximum limit has been reached',
      withdraw_incorect_count_per_day:
        'Incorrect, quantity of active withdraw per day higher than allowed one',
      withdraw_max_user_limit_error:
        'Incorrect max amount, higher than max amount',
      amount_greater_than: 'Amount must be greater than',
      verification_required: 'The verification process is required',
    },
    info: {
      amount: 'Amount',
      iban: 'IBAN',
      bank_add: 'Bank Address',
      bank_name: 'Bank Name',
      client_name: 'Client Name',
      payment_com: 'Payment comment',
      acc_captcha_not_active:
        'To authorize on the platform, go to the captcha verification',
      acc_not_activated:
        'To authorize on the site, follow the link from the email',
      approximately_amount:
        'This amount is approximate and is used for informational purposes only.',
      old_pass_incorrect: 'Old Password is incorrect',
      incorrect_captcha: 'Code from captcha is incorrect',
      code_incorrect: 'Code is incorrect',
      fiat_unavailable: 'Order creation is temporarily unavailable',
      fiat_warning:
        'Attention! When paying for the application, be sure to indicate a comment to the payment. The comment should not contain anything other than the digit code above.',
      fiat_big_amount: 'Cannot withdraw this amount now, try again later',
      expired_link: 'Sorry, this link is no longer valid',
      not_foundes: 'PAGE NOT FOUND',
      back_home: 'Return to Home page',
      canceled_withdrawal: 'Withdraw is canceled',
      no_address: 'Sorry, you have no refill address',
      no_image: 'Sorry, no image available',
      email_not_found: 'User with this email is not found',
      unable_to_create_refill: 'Refill is temporary unavailable',
      internal_err: 'Internal error',
      minimal_pair_amount:
        'Cannot create the order. Amount is less then minimal for this pair',
      not_support_chars: "We don't support the following characters: ",
      ver_fio_step_required: 'Please set your name to reach the next step',
      no_documents_uploaded: 'No documents uploaded',
      document_is_not_uploaded: 'Document is not uploaded',
      username_not_set: 'Please set the account owner credential first',
      website_address_not_valid: 'website address is not a valid address',
      disable_security_auth:
        '2 factor authorization is already enabled. Disable the current one first',
      security_auth_code_req_block: 'Secret code is already sent',
      no_orders_in_book: 'There are no orders from which to take the rate now',
      need_login_first: 'Please login first.',
      not_validation_file: 'Invalid file',
      not_save_file: 'File was not uploaded',
      file_was_not_uploaded: 'Invalid document',
      error_else: 'Unknown server error',
      reguired_2fa_antiphising:
        'To create and change the Anti-Phishing Code, you need to activate 2FA.',
    },
    success: {
      account_activated: 'Account successfully activated',
      account_type_set: 'Account type successfully set',
      account_type_reset: 'Account type reset',
      data_sent: 'Data successfully sent to server',
      data_is_copied: 'Data successfully copied to buffer',
      fiat_on_moderation: 'Payment confirmed',
      fiat_refill_canceled: 'Refill is canceled',
      success_login: 'Login Successful',
      change_pass: 'Password successfully changed',
      add_to_book: 'Address added to AddressBook',
      processing_order: 'Order is sent for processing!',
      order_delete: 'Order deleted',
      document_deleted: 'Document deleted',
      withdraw_create: 'Withdraw request created, confirm please',
      fiat_refill_create: 'Refill request created, wait for moderation',
      request_create: 'Request created',
      code_confirm: 'Code confirmed proceed next',
      acc_sec_code_sent_mail: 'Secret code sent to your mail, please check',
      acc_sec_code_sent_google:
        'Secret code sent to your google app, please check',
      recovery_send: 'Recovery link has been sent to your Email',
      recovery_send_forgot:
        'If there is a user account associated with the email address you provided, we will send you the next steps required to reset your password',
      success_registration: 'Registration completed',
      registration_activation_need:
        'Link with account activation has been sent to your email',
      send_mess: 'Your message is sent',
      news_subscription:
        'You have been successfully subscribed to our newsletter, promotions and announcements by email',
      news_un_subscription:
        'You have been unsubscribed for our news, promotions and announcements',
      confirmation_sent_to_email:
        'Order successfully created. Confirmation link has been sent to your email',
      upload_file_success: 'Verification document uploaded',
      delete_file_success: 'Verification document deleted',
      antiphishing_installed:
        'Anti-Phishing code has been successfully installed',
    },
  },
  validation: {
    required_email: 'The "Email" field is required',
    enter_correct_email: 'Enter a valid email',
    required_password: 'The "Password" field is required',
    required_repeat_password: 'The "Repeat password" field is required',
    incorrect_old_password: 'Incorrect old password',
    password_format:
      'The "Password" field must contain at least 6 chars: uppercase (A-Z) lowercase (a-z), digits (0-9)',
    anti_phishing_format:
      'Please enter 4-20 non-special characters: uppercase (A-Z) lowercase (a-z), digits (0-9)',
    repeat_password_not_valid: 'The "Repeat password" value is not valid',
    you_have: 'You have',
    tries_left: 'tries left',
    try_left: 'try left',
    attempt_limit: 'Attempt limit exceeded, try again later',
    must_be_at_least: 'Field must be at least',
    required_theme: 'The "Theme" field is required',
    required_message: 'The "Message" field is required',
    field_is_required: 'Field is required',
    input_correct_social: 'Please enter correct social link',
    code_field_required: 'Code field is required',
    amount_field_required: 'The "Amount" field is required',
    address_field_required: 'The "Address" field is required',
    address_is_invalid: 'Address is invalid',
    currency_required: 'The Currency field is required',
    address_label_required: 'The Address label field is required',
    wallet_address_required: 'The Wallet address field is required',
    address_book_add: 'The address was successfully added to the Address Book',
    address_book_deleted: 'The address has been removed from the Address Book',
  },
  footer: {
    about_us: 'About us',
    about: 'About',
    terms_of_use: 'Terms of Use',
    privacy_policy: 'Privacy Policy',
    cookies_policy: 'Cookies Policy',
    risk_and: 'Risk Disclosure Statement',
    aml_kyc: 'AML & KYC Policy',
    security: 'Security',
    news: 'News',
    service: 'Service',
    curr_and_tokens: 'Currencies and Tokens',
    fees: 'Fees',
    referral: 'Referral',
    mobile_app: 'Mobile App',
    status_online: 'Status Online',
    support: 'Support',
    submit_request: 'Submit a request',
    api_documentation: 'API Documentation',
    apply_to_list: 'Apply To List',
    community: 'Community',
    channel: 'channel',
    chat: 'chat',
    all_rights: 'All rights reserved',
    bug_bounty: 'Bug Bounty',
  },
  support_and_faq: 'Support and Frequently Asked Questions',
  about_coocies_modal: {
    main_text:
      'Our website is using cookies to provide you with service of the highest quality as possible, analyze our traffic, and for security and marketing purposes. By visiting our website, you agree to our use of cookies.',
    link_text: 'Read more about cookies',
    accept: 'Accept',
  },

  two_fa_modal: {
    title: '2FA check',
    enter_2fa_code: 'Enter 2FA code here',
    type_2fa_code: 'Enter {data} 2fa code here',
    code_is_sent: 'Enter Email code',
    code_is_sent_google: 'Enter Google Authenticator code',
    two_fa_code_sent: 'Two-factor authentication code is sent to your email',
    google_2fa: {
      p_1: "The first step is to download the Google Authenticator app for your Android or iOS device. If you need help getting started, please see Google's Support Page.",
      p_2: 'If you do not have access to the Android Market or App Store, there are other options for getting Google Authenticator: Android Download, Google Chrome Plugin or iTunes App Store.',
      p_3: 'After You get the code, paste it here and send to server.',
      scan_qr: 'Scan the QR code',
      enter_token: 'Enter the token below',
      p_4: 'The token will not be shown again after 2FA is enabled. If you have multiple devices, add your account token to a safety note before clicking enable. (Note: Your Account Token will change each time you reload your browser',
    },
    resend: 'Resend',
  },
  password_change_modal: {
    title: 'Change Password',
  },
  anti_phishing_modal: {
    title_create: 'Create Anti-Phishing Code',
    title_change: 'Change Anti-Phishing Code',
    input_label: 'Anti-phishing Code',
  },
  confirm_withdraw_modal: {
    title: 'Standard security check',
    this_action_requires: 'This action requires an additional security check.',
    enter_code: 'Enter the code to proceed',
    enter_number_placeholder: 'Enter confirmation number',
    confirmation_step: 'Confirmation step',
  },
  link_to_email_modal: {
    link_sent:
      'Withdraw confirmation link was sent to your email. Please follow it to confirm your withdrawal order.',
    go_to_withdraw_history: 'Go to withdrawal history',
    go_to_email: 'Go to email',
  },
  timer_modal: {
    unavailable: 'The withdrawal will be available through',
    login_timer: 'The withdrawal will be available through',
    password_timer:
      'After changing the password, the withdrawal is temporarily blocked',
    hours: 'hours',
    min: 'min',
    sek: 'sec',
  },
  qr_code_modal: {
    text: 'Scan the QR code and get a referral link',
  },
  confirmation_messages: {
    please_await: 'Please wait for the confirmation link',
    withdrawal_confirmed: 'Withdrawal confirmed successfully',
    withdrawal_canceled: 'Withdrawal canceled successfully',
    refill_canceled: 'Refill canceled successfully',
    code_not_valid: 'Sorry, this code is not valid',
    link_activated:
      'Link is now successfully activated. This step will lead withdraw order to moderation process. If You want to cancel the order, please click the Cancel button, or press confirm to proceed',
  },
  games: {
    games: 'Games',
    low_balance: 'Not enough on balance',
  },
  futures: {
    buy: 'Buy/Long',
    sell: 'Sell/Short',
  },
  vip: {
    title: 'Your Trading Fee Level',
    highest_level: 'Your VIP level is the highest',
    to_upgrade_to: 'To upgrade to',
    trade_another: 'trade another',
    trade_market: 'in spot trade market',
    and: 'and',
    increase_balance: 'increase your {iso} balance by ',
    limit: 'Limit',
    market: 'Market',
    trade_turnover: 'Spot Trade Turnover',
    your_balance: '{iso} Balance',
    level: 'Level',
    trade__Turnover: 'Trade Turnover',
    or: 'or',
    balance: '{iso} Balance',
    you_will_need: 'you will need to',
    days_in: 'd in',
    discount_text: '{iso} Discount',
    commission_toggle: 'Allow payment of trading fees using {iso}',
    commission_notification_allow:
      'Payment of trading fees using {iso} allowed',
    commission_notification_disallow:
      'Payment of trading fees using {iso} disallowed',
    discount_status_info:
      'Enabling {iso} discount you will pay all the fees using {full_iso} coin',
    discount_status: '{iso} discount status',
    enabled: 'Enabled',
    disabled: 'Disabled',
    buy: 'buy {iso}',
    baner_commission_exclamation: '',
    baner_commission: 'Save {percent}% from fees using {iso} Coin',
    baner_commission_disabled: 'Save {percent}% from fees using',
    iso_coin_disabled: '{iso} Coin',
  },
  qrCodeCamera: {
    not_allowed_error: 'ERROR: you need to grant camera access permission',
    not_found_error: 'ERROR: no camera on this device',
    not_supported_error: 'ERROR: secure context required (HTTPS, localhost)',
    not_readable_error: 'ERROR: is the camera already in use?',
    over_constrained_error: 'ERROR: installed cameras are not suitable',
    stream_api_not_supported_error:
      'ERROR: Stream API is not supported in this browser',
    insecure_context_error:
      'ERROR: Camera access is only permitted in secure context. Use HTTPS or localhost rather than HTTP.',
    other_error: 'ERROR: Camera error ({error})',
  },
  recaptcha_badge: {
    text_start: 'This site is protected by reCAPTCHA and the Google',
    text_policy: 'Privacy Policy',
    text_and: 'and',
    text_terms: 'Terms of Service',
    text_apply: 'apply.',
  },
  email_confirmation_modal: {
    title: 'Withdraw Confirmation Code',
    description:
      'The withdrawal confirmation code has been sent to your email. Please check your email and enter the code below.',
  },
}