export default {
  add: 'Adaugă',
  remove: 'Șterge',
  new: 'Nou',
  demo: 'Demo',
  get: 'Obtineti',
  receive: 'Obtineti',
  check: 'Check',
  vote: 'Voteaza',
  show_more: 'Afișează mai mult',
  read_more: 'Citește mai departe',
  show_less: 'Afișează mai puțin',
  no_records: 'Nu s-au găsit înregistrări',
  no_favorites: 'Nu s-au găsit elemente favorite',
  no_data: 'Nu există date',
  or: 'sau',
  copy: 'Copiază',
  close: 'Închide',
  change: 'Modifică',
  submit: 'Trimite',
  disable: 'Dezactiveaza',
  enable: 'Activeaza',
  coming_soon: 'In curand',
  delete: 'Șterge',
  send: 'Trimite',
  send_code: 'Trimite codul',
  other_news: 'Alte știri',
  all_news: 'Toate Știrile',
  welcome: 'Bun Venit!',
  cancel: 'Anulează',
  back: 'Înapoi',
  confirm: 'Confirmă',
  next: 'Următorul',
  search: 'Caută',
  ask_question: 'Pune o întrebare',
  to_balance_page: 'Catre balanta',
  share: 'Distribuie',
  join_us: 'Alătură-te',
  published: 'Publicat',
  sent_modal: 'Trimite',
  password_change: 'Parola schimbata',
  enable_cookies_app: 'This feature does not work without cookies',
  value_not_found: 'Valoare inexistenta',
  time: {
    day: 'zi | zile',
    hour: 'ora | ore',
    min: 'min',
    sec: 'sec',
  },
  fiat_widthrow: {
    order_canceled: 'Comanda anulata',
    success_link:
      'Comanda creata cu succes. Linkul de confirmare a fost trimis pe email',
    success_coin:
      'Link-ul de confirmare a fost trimis pe email-ul tău. Te rugăm să verifici și să confirmi',
    success_coin_2: 'Codul 2fa a fost trimis pe email',
    success: 'Linkul de confirmare a fost trimis pe adresa ta de e-mail',
    error: 'Error validate pin code',
    activated: 'Linkul este acum activatcu succes',
    err_activated: 'Ne pare rău, acest cod nu este valid',
  },
  meta: {
    main_title: 'Crypto Exchange Romania | Coinzix ',
    main_description:
      'Coinzix Cryptocurrency Exchange - Cumpara si vinde criptomonede pe una dintre cele mai convenabile si fiabile platforme crypto.',
    markets_title: 'Preturi Criptomonede | Coinzix',
    markets_description:
      'Vezi timp real pret bitcoin, pret ethereum, sau alte altcoins in Romania pe platforma de cripto exchange Coinzix. ',
    trading_title: '{rate} | {pair} | Spot Trading | Coinzix',
    login_title: 'Log In | Coinzix',
    login_description:
      'Intra in cont folosind adresa de e-mail si parola. Utilizatorii conectati pot cumpara, vinde si schimba criptomonede.',
    about_title: 'Despre noi | Coinzix',
    about_description:
      'Afla mai multe despe Coinzix, o platforma de crypto exchange specializata in cripto trading si technologie block chain.',
    terms_and_conditions_title: 'Termeni si Conditii | Coinzix',
    terms_and_conditions_description:
      'Citeste termenii si conditiile platformei de cripto trading Coinzix, inainte de a tranzactiona.',
    privacy_policy_title: 'Politica de Confidentialitate| Coinzix',
    privacy_policy_description:
      'Citeste politica de confidentialitate a platformei de cripto trading Coinzix, inainte de a tranzactiona.',
    cookies_policy_title: 'Politica cookie-urilor | Coinzix',
    cookies_policy_description:
      'Folosim cookie-uri pentru a personaliza continutul si reclamele cat si pentru a analiza traficul nostru. Citeste mai multe despre politica cookie-urilor aici.',
    risk_disclosure_statement_title:
      'Declaratia Privind Divulgarea Riscului | Coinzix',
    risk_disclosure_statement_description:
      'Citeste declaratia noastra de divulgara riscului inainte de a incepe sa tranzactionezi, pentru a te asigura ca cunosti riscurile asociate crypto tradingului.',
    currencies_tokens_title: 'Criptomonede si Curs | Coinzix',
    currencies_tokens_description:
      'Urmareste lista noastra completa criptomonede clasificate dupa volum, 1 inch, curs, capitalul pietei, schimbarea din ultimile 24 de ore si multe altele.',
    fees_title: 'Taxe si Comisioane | Coinzix',
    fees_description:
      'Afla care sunt taxele si comisioanele percepute de platforma de cripto exchange Coinzix.',
    pair_description:
      'Cel mai important cryptoexchange din Romania. Complet reglementat. Cumpărați, vindeți și tranzacționați o varietate de cryptomonede, inclusiv {pair}!',
    status_online_title: 'Status Online | Coinzix',
    status_online_description:
      'Vezi lista noastra completa de criptomonede clasificate dupa ultima tranzactie reusita, timpul mediu de procesare sau sunt disponibile tranzactiile online.',
    submit_request_title: 'Trimite O Cerere | Coinzix',
    submit_request_description:
      'Contactati-ne pentru orice intrebari sau solicitari pe care le aveti cu privire la schimbul de criptomonede pe platforma de crypto exchange Coinzix.',
    support_title: 'Suport | Coinzix',
    support_description:
      'Echipa noastra este disponibila 24/7 pentru a va raspunde la intrebari si pentru a va oferi asistenta cu privire la orice problema pe care o intampinati in trading.',
  },
  margin: {
    transfer: 'Transfer',
    from: 'De la',
    ex_wallet: 'Portofel Tranzactionare',
    margin_wallet: 'Portofel Marja',
    to: 'Către',
    coin: 'Moneda',
    amount: 'Cantitate',
    available: 'Disponibil',
    confirm_transfer: 'Confirma Transferul',
    active_position: 'Pozitii Active',
    positions_history: 'Istoric Pozitii',
    funds: 'Fonduri',
    profit_rate: 'Rata Profit',
    loss_rate: 'Rata Pierderi',
    notifiration_approve: 'Retragerea a fost confirmate cu succes',
    notifiration_canceled: 'Retragerea a fost anulate cu succes',
  },
  header: {
    nav: {
      free_coins: 'Free Coins',
      demo_trading: 'Trading demo',
      social_listing: 'Listă Social',
      news: 'Știri',
      trade: 'Schimbă',
      spot_trading: 'Tranzacții Instant',
      spot_exchange: 'Schimb Instant',
      wallet: 'Portofel',
      launchpad: 'Launchpad',
      account_dropdown: {
        account: 'Cont',
        security: 'Securitate',
        verification: 'Verificare',
        referral: 'Program Fidelizare',
        vip: 'Nivel VIP',
        api_management: 'API Management',
      },
      balance: 'Portofel',
      support: 'Suport',
      contacts: 'Contacte',
      fees: 'Comisioane',
      exchange: 'Schimb',
      markets: 'Piețe',
      staking: 'Staking',
      partner_news: 'Știri',
      blog: 'Blog',
      margin: 'Marjă',
      buy_crypto: 'Cumpara Crypto',
      buy_crypto_card: 'Card Debit/Credit',
      buy_crypto_with_card: 'Cumpara crypto cu cardul',
      buy_fiat_euro: 'Depoziteaza Euro',
      buy_fiat_bank_euro: 'Depoziteaza euro prin transfer bancar',
    },
    logbox: {
      log_in: 'Autentificare',
      or: 'sau',
      log_out: 'Deconectare',
      sign_in: 'Autentificare',
      sign_up: 'Înregistrare',
      sign_up_now: 'Incepe Inregistrarea',
      forgot: 'Am uitat parola',
      restore: 'Recuperare Parola',
      setNewPass: 'Setează noua parolă',
    },
  },
  mob_nav: {
    graph: 'Grafic',
    menu: 'Meniu',
  },
  twofactor: {
    activ: '2 FA activeaza',
    deactiv: '2 FA dezactiveaza',
  },
  subscribe: {
    success_subscribe: 'Abonament de succes',
    success_unsubscribe: 'Dezabonare cu succes',
  },
  TwoFA: {
    active: '2 FA activeaza',
    not_active: '2 FA dezactiveaza',
    google_TwoFA:
      'Autentificarea in 2 pasi este deja activa. Dezactiveaza prima data varianta curenta',
  },
  referal: {
    ref_link: 'Link de afiliere copiat',
  },
  feedback: {
    feedback_notify: 'Multumim pentru recenzia ta',
  },
  landing_page: {
    title_text_strong: 'CUMPARA SI VINDE CRYPTOMONEDE',
    title_text_regular:
      'UNA DINTRE CELE MAI CONVENABILE SI FIABLIE PLATFORME CRYPTO',
    title_text_sub: 'VERSIUNEA BETA',
    title_text_top_reg: 'INREGISTREAZA-TE ACUM',
    title_text_top_buy: 'Cumpara acum',
    title_text_reg: 'INREGISTREAZA-TE ACUM PRIN CATIVA PASI SIMPLI',
    proven_platform:
      'Platforma de tranzacționare și investiții profitabile dovedite',
    start_trading: 'Începe tranzactionarea',
    create_and_start: 'Crează-ți contul și începe imediat',
    whole_list: 'Toată lista',
    blocks: {
      link_x_platform: 'X-Platform pentru lansare IEO',
      link_analytics: 'Analiză de piață profesională',
      text_processing_speed:
        'Procesarea tranzacțiilor rapide și a conexiunilor TCP',
      text_guaranteed: 'Securitate premium împotriva atacurilor hackerilor',
      link_support_24: '24/7 Suport Online',
      text_more_than: 'Peste 90% din monede in portofelele de tip cold',
      link_api: 'Documentație API',
      text_user_friendly:
        'Interfață grafică ușor de utilizat avand toate instrumentele de care aveți nevoie',
    },
  },
  auth_page: {
    email: 'Email',
    password: 'Parolă',
    oldPassword: 'Parola veche',
    passRepeat: 'Repetă parola',
    userName: 'Nume utilizator',
    createAccount: 'Creează Cont Nou',
    open_account: 'Creează Cont',
    confirm: 'Confirmă',
    forgot_pass: 'Ai uitat parola?',
    timezone: 'Fus orar',
    agree_checkbox: {
      agree: 'Sunt de accord cu ',
      terms_of_use: 'Termenii de Utilizare',
      privacy_policy: 'Politica de Confidențialitate',
      and: 'și',
      ending: '',
      lang: '',
      confirmation_required: 'Câmpul de confirmare este obligatoriu',
    },
    already_have: 'Ai deja cont?',
    forgot_password_title: 'Resetare parolă',
    resend_activation_title:
      'Contul tau inca nu este activat. Te rugam sa iti verifici adresa de email.',
    resend_activation_text_1:
      'Daca nu ai primit nici un email, verifica folderul spam sau apasa',
    resend_activation_button: 'click aici',
    resend_activation_text_2: 'pentru a-l retrimite din nou',
  },
  captcha: {
    click_to_verify: 'Click să verifici',
    verification_success: 'Înregistare cu succes',
  },
  faq: {
    registration: 'Înregistrare și Autentificare',
    registration1: '1. Înregistrare și Autentificare',
    general: 'Introducere Generală',
    list: 'Lista monedelor',
    comission: 'Informații despre comisioane',
    data: 'Securitatea datelor',
    verification: 'Verificare',
    functionality: 'Funcționalitatea site-ului',
    confirm: '2. Nu am primit o confirmare pe email, ce trebuie să fac?',
    reasons:
      'Există 4 motive posibile care pot face ca o astfel de situație să se întâmple: 1. Clientul tău de e-mail ne blochează e-mailurile. 2. E-mailul a intrat în spam. 3. Email-ul tău este plin și nu mai are capacitatea de a accepta email-uri noi. 4. Parola ta nu îndeplinește cerințele sistemului nostru, așa că nu a fost trimis un e-mail cu un link de confirmare. Te rugăm să contactezi echipa noastră de asistență și te vom ajuta să rezolvi problema',
  },
  withdraw: {
    popup:
      'Linkul de confirmare a fost trimis pe emailul tău. Te rugăm să verifici și să confirmi',
    error_address: 'Adresa acestei monezi nu poate fi găsită',
  },
  profile: {
    title: 'Profil',
    account: {
      title: 'Cont',
      email: 'Email',
      user_name: 'Utilizator',
      password: 'Parolă',
      language: 'Limbă',
      lang_en: 'English',
      lang_ro: 'Română',
      lang_ru: 'Русский',
      lang_ua: 'Українська',
      time_zone: 'Fus Orar',
      notify_me:
        'Anunță-mă cu privire la orice știri, promoții sau anunțuri prin e-mail',
      we_ensure:
        'Garantăm stocarea în siguranță și confidențialitatea datelor tale. Dacă ai întrebări suplimentare, te rugăm să nu eziți ',
      contact_us: 'să ne contactezi',
      support: 'Suport',
      address_book: {
        title: 'Agendă',
        withdrawing_crypto:
          'Retragerea criptomonedelor de pe platforma noastră necesită specificarea unei adrese de destinație. Agenda de adrese este destinată etichetării și salvării adreselor de destinație pentru o utilizare mai ușoară ulterior. Când faci vreo retragere, poți selecta rapid și ușor o adresă din agendă.',
        table: {
          iso: 'ISO',
          address: 'Adresă',
          iso_new: 'Monedă',
          label: 'Etichetă',
          add_to_address_book: 'Adaugă în agendă',
          currency: 'Monedă',
          address_label: 'Etichetă adresă',
        },
      },
    },
    whitelist: {
      title: 'Lista Permisă de Retrageri',
      whitelist: 'Lista Permisă',
      body_text:
        'Adăugarea de adrese în agendă marcată ca "Lista Permisă de Retrageri" asigură protecția fondurilor tale, permițând retragerile numai către aceste adrese.',
      please_activate_2fa: 'Te rugăm să activezi 2FA.',
      please_activate_2fa_book:
        'Pentru a adăuga adresa portofelului în Lista Permisă, te rugăm să activezi 2FA.',
      add_to_white_list: 'Adaugă în Lista Permisă',
      success_enable: 'Lista permisă de retrageri a fost activată cu succes',
      success_disable:
        'Lista permisă de retrageri a fost dezactivată cu succes',
      book_enable:
        'Adresa portofelului a fost adăugată cu succes în Lista Permisă de Retrageri',
      book_disable:
        'Adresa portofelului a fost ștearsă cu succes din Lista Permisă de Retrageri',
    },
    security: {
      title: 'Securitate',
      account_token: 'Token cont (cheie)',
      please_consider:
        'Te rugăm să iei în considerare opțiunile disponibile pentru creșterea securității contului tău. Vrem să te asigurăm că la noi, contul tău este securizat.',
      do_not_share_codes:
        'Te rugăm să nu divulgi sau să distribui parola, codurile de autentificare Google sau e-mail către nimeni, inclusiv asistența Coinzix.',
      still_have_questions: 'Încă ai nelămuriri? Cere asistență',
      email_authorization: 'Autorizare Email',
      each_time_you_login_email:
        'De fiecare dată când te autentifici, un cod unic va fi trimis la adresa ta de e-mail',
      google_authorization: 'Autorizare Google App',
      each_time_you_login_google:
        'De fiecare dată când te autentifici, va fi necesar un nou cod de autorizare din aplicația Google',
      antifishing_code: 'Cod Anti-phishing',
      antifishing_text1:
        'Te rugăm să te asiguri că utilizezi opțiunile noastre de securitate disponibile pentru a crește securitatea contului dvs. Instalați un cod anti-phishing pentru a distinge notificările și e-mailurile Coinzix autentice de diferite încercări de phishing.',
      device_management: 'Management Dispozitive',
      device: 'Dispozitiv',
      date: 'Data',
      location: 'Locație',
      ip_address: 'Adresă IP',
    },
    vip: {
      title: 'Nivel VIP',
      label: 'nou',
    },
    verification: {
      title: 'Verificare',
      to_deposit_or_withdraw:
        'Pentru a depune sau retrage USD sau alte monede de tip FIAT, detaliile contului tău trebuie verificate pentru a respecta toate legile și cerințele relevante ale autorităților de reglementare pentru combaterea spălării banilor și finanțării terorismului.',
      has_developed:
        'a dezvoltat un proces de verificare online, în care este necesară completarea unui formular de aplicare și atașarea documentelor însoțitoare. În plus, va trebui să descărci, să semnezi și să trimiți o declarație care să confirme corectitudinea acestor informații și',
      projects_permission: 'are permisiune sa verifice.',
      choose_type: 'Alege tipul',
      project_offers:
        'oferă două tipuri de conturi. Pentru a continua, alege o opțiune',
      please_note: 'Nu uita',
      all_documents:
        'Toate documentele furnizate trebuie să fie în alfabet român/latin sau o traducere certificată în limba engleză.',
      all_files:
        'Toate fișierele încărcate trebuie să fie în .pdf, .jpg sau .jpeg.',
      all_fields:
        'Toate câmpurile din următorul formular de verificare sunt obligatorii (poate fi utilizat NA pentru Neaplicabil).',
      to_avoid:
        'Pentru a evita posibile întârzieri, te rugăm să te asiguri că verifici corectitudinea documentelor înainte de trimitere. Te rugăm să verifici să nu trimiți același document de două ori și, eventual, să uiți unul.',
      here_you_can_track:
        'Aici poți urmări procesul de verificare. Te rugăm să completezi toate secțiunile de mai jos. De îndată ce toate secțiunile sunt completate și documentele sunt furnizate, echipa noastră de auditori va începe să verifice toate informațiile solicitate și să îți confirme contul.',
      still_have_questions: 'Încă mai ai întrebări? Cere asistență',
      you_may_reset: 'Poți să îți resetezi contul',
      reset: 'Resetare',
      avg_time_complete:
        'Durata medie de completare a solicitării este de aproximativ 1 oră, dar procesarea poate dura mai mult si până la 24 de ore.',

      form: {
        name: 'Nume',
        submitted: 'Trimis',
        approved: 'Aprobat',
        information_for:
          'Informații pentru identificarea autentică a titularului contului',
        to_change:
          'Pentru a modifica datele de autentificare deja configurate, vizitează',
        begin: 'Începe',
        address: 'Adresa',
        location_info: 'Informații despre locație pentru o măsurare fiabilă.',
        manage_documents: 'Administrează documente',
        view_existing:
          'Vezi documentele existente și adaugă altele noi. Este de preferat să descarci fișierele suplimentare solicitate sau să înlocuiești documentele învechite.',
        enter_name_first: 'Întrodu numele tău ca prim pas',
        first_name: 'Prenumele',
        last_name: 'Numele',
        middle_name: 'Al doilea prenume',
        gender: 'Sex',
        female: 'Feminin',
        male: 'Masculin',
        enter_address: 'Introdu adresa ta',
        country_state: 'Țară / Județ',
        city: 'Localitate',
        street: 'Strada',
        post_code: 'Cod poștal',
        select_document: 'Alege documentul și tipul lui',
        select_file: 'Alege un fișier...',
        please_select_file_err: 'Te rugăm să alegi un fișier',
        please_choose_type_err: 'Te rugăm să alegi tipul documentului',
        size_error: 'Marimea fișierul depășește limita admisă',
        format_error: 'Acest tip de fișier nu este suportat.',
        choose_doc_type: 'Alege tipul documentului',
        please_formats:
          'Te rugăm să încarci fișierul într-unul dintre următoarele formate acceptate: PDF, PNG, JPEG. Dimensiunea maximă a fișierului este de 5 Mb.',
        uploaded_docs: 'Documente încărcate',
        upload_time: 'Timp de încărcare',
        status: 'Stare',
        type: 'Tip',
        doc_on_moderation: 'În procesare',
        doc_approved: 'Aprobat',
        doc_canceled: 'Anulat',
        doc_declined: 'Respins',
        doc_passport: 'Pașaport',
        doc_drivers_lic: 'Permis de Conducere',
        doc_id_card: 'Carte de Identitate',
        doc_bank_statement: 'Extras de Cont',
        doc_util_bills: 'Factură Utilități',
      },
      individual_account: {
        title: 'Cont individual',
        account_on_behalf: 'cont în numele unei persoane',
        verification_requirements: 'Cerințe de verificare',
        complete_form: 'Completează formularul online.',
        age: 'Vârsta: Cel puțin 18 ani.',
        information: 'Informații: număr de telefon, adresă de email și adresa.',
        identification:
          'Identificare: două documente de identificare valabile emise de guvern cu poză; adică pașaport, carte de identitate națională, permis de conducere, carte de rezidență, permis de muncă etc.',
      },
      corporate_account: {
        title: 'Cont persoana juridica',
        account_on_behalf:
          'cont în numele unei corporații, persoane juridice, parteneriate sau fundații',
        verification_requirements: 'Cerințe de verificare',
        complete_form: 'Completează formularul online',
        corporate_documents: 'Documente corporative',
        director_information:
          'Informații despre director: fiecare administrator, acționar semnificativ și ofițer (i) de control trebuie să furnizeze identificarea. Te rugăm să consulți formularul online pentru a afla mai multe despre noi.',
        after_completing:
          'După completarea formularului de verificare pentru persoane juridice, va trebui completat un formular individual pentru fiecare director al organizației tale, acționari semnificativi și ofițeri de control.',
      },
      referral_title: 'Program de fidelizare',
    },
    referral: {
      get_link: 'Primește un link',
      reg_and_copy: 'Înregistrează și copiază linkul de recomandare',
      inv_friends: 'Invită-ți prietenii',
      inv_friends_to_reg:
        'Invită-ți prietenii să se înregistreze folosind linkul de recomandare și să obțină recompense odată ce finalizează o tranzacție',
      get_rewards: 'Obține recompense',
      receive_up_to: 'Primește până la {data}% comision în timp real',
      about_program: 'Despre Program',
      ref_link: 'Link de recomandare',
      demo_warning:
        'Programul de fidelizare funcționează în modul demo; în prezent nu sunt alocate bonusuri în numerar',
      support_level:
        'sprijină sistemul de fidelizare la nivel {levels}. Fiecare nivel are propriul său %, care este egal cu {first}% pentru primul',
      support_level_2: ', {percent}% pentru al doilea',
      support_level_3: ' și {percent}% pentru al treilea nivel',
      all_ref_data: 'Toate datele programului de fidelizare',
      my_refs: 'Recomandările mele',
      total_earnings: 'Total câștiguri',
      refs_with_rate: 'Referința curs',
      email: 'Email',
      earnings: 'Câștiguri',
      reg_date: 'Data înregistrării',
      count: 'Număr',
      ref_rate: 'Curs',
      level: 'Nivel',
      oops: 'Oops, se pare că ești deja autentificat',
    },
    api_management: {
      title: 'API Management',
      label: 'nou',
      save: 'Salveaza',
      cancel: 'Anuleaza',
      input_label: 'Denumiți cheia API pentru a continua',
      input_required_error: 'Introduceți eticheta dorita pentru API Key',
      submit_button: 'Creați API',
      api_info: {
        1: 'Fiecare cont poate crea până la 10 chei API.',
        2: 'Nu dezvăluiți nimănui cheia dvs. API pentru a evita pierderile de monede din cont. Este recomandat să legați IP-ul dumneavoastră de cheia API pentru a crește securitatea contului.',
        3: 'Rețineți că aceste chei API pot fi dezvăluite prin autorizările pe care le dați către platforme terțe.',
        4: 'Vă recomandăm să efectuați KYC înainte de a crea API.',
      },
      subtitle: 'Lista API-uri',
      delete_all: 'Sterge toate API',
      locked: 'Blocat',
      edit: 'Editeaza restrictiile',
      delete: 'Sterge',
      qr: 'Scaneaza pentru a obtine adresa',
      key_label: 'Cheie API',
      secret_key_label: 'Cheie Secreta',
      restriction_label: 'Restrictii API',
      ip_access_label: 'Restrictii acces IP',
      restriction: {
        read: 'Vizualizeaza',
        spot: 'Permite tranzactionare spot',
        withdrawal: 'Permite retrageri',
      },
      ip_access: {
        all: 'Fara restrictii (Securitate slaba)',
        trusted:
          "Restrictioneaza accesul doar pentru IP'urile de incredere (Recomandat)",
      },
      ip_access_trusted_placeholder:
        "Cand introduceti mai multe ip'uri va rugam sa le separati prin tasta spatiu",
      ip_access_trusted_required: "Introduceti Ip'ul de incredere",
      ip_access_trusted_incorrect:
        "Va rugam sa introduceti ip'urile de incredere corecte separate prin spatiu",
      modal: {
        title: 'Verificare de securitate',
        verification_email: 'Cod de verificare E-mail',
        verification_email_required: 'Este necesar codul de verificare E-mail',
        twofa_email: 'Cod de verificare 2FA E-mail',
        twofa_email_required: 'Codul de verificare 2FA Email este necesar',
        twofa_google: 'Cod 2FA Google',
        twofa_google_required: 'Codul 2FA Google este necesar',
        code_incorrect: 'Cod incorect',
      },
      notifications: {
        create: 'Api creat',
        delete: 'Api sters',
        update: 'Api actualizat',
        add_deleted: "Toate Api'urile sterse",
      },
    },
  },
  landing_table: {
    search_coin_name: 'Caută numele monedei',
    favorites: 'Favorite',
    all: 'Toate',
    markets: 'Piețe',
    markets_last: 'Piețele',
    pair: 'Perechi',
    coin: 'Monedă',
    change: 'Modifică',
    last_price: 'Ultimul Preț',
    high_24: 'Maxim 24h',
    low_24: 'Minim 24h',
    h_24: '24h',
    volume: 'Volum',
    tickers: 'Tickere',
    vol: 'VOL',
    trade: 'Tranzacție',
    show_more: 'Afişează mai mult',
  },
  fiat_info: {
    incorrect: 'Cod Incorect',
    require: 'Suma Este Obligatorie',
    zero_amount: 'Value must be greater than 0',
    err: 'Codul de Referinta Este Obligatoriu',
    err_max_length:
      'Lungimea maximă de referință pentru câmpul beneficiarului este de ',
    fee: 'Comision Retragere',
    ben_err_acc: 'Contul Beneficiarului Este Obligatoriu',
    ben_err_acc_max_length:
      'Lungimea maximă a contului beneficiarului de câmp este de ',
    ben_err: 'Numele Beneficiarului Este Obligatoriu',
    ben_err_max_length: 'Lungimea maximă a câmpului Beneficiarului este de ',
    bank_err: 'Numele Numele băncii Obligatoriu',
    bank_err_max_length: 'Lungimea maximă a Field Bank Name este de ',
    ben_name: 'Nume beneficiar',
    ben_acc: 'Cont beneficiar',
    balance: 'Balanta Cont',
    reserved: 'rezervat',
    turnover: 'This Mounth Turnover',
    outbound: 'Outbound',
    inbound: 'Inbound',
    send: 'Trimite',
    ben_ref: 'Referinta beneficiar',
    comment: 'Cometariu',
    bank_name: 'Numele băncii',
    deposit_limit: 'Depășirea limitelor privind depozitele fiat',
    withdraw_limit: 'Depășirea limitelor de retragere fiat',
  },
  fiat_refill_info: {
    amount_required: 'Campul cantitate este necesar',
    amount_min_value: 'Suma minima de incarcare este de',
  },
  verify: {
    status: 'Verificarea stării',
    level: 'Nivel',
    level_0: 'Nivel 0',
    level_1: 'Nivel 1',
    level_2: 'Nivel 2',
    complete: 'Verificat',
    in_process: 'Porniți verificarea',
    not_verified: 'Nu e verificat',
    l_deposit: 'Depozit crypto: nelimitat',
    l_withdraw: 'Retrageri crypto: {amount} {currency}/zi',
    l_fiat: 'Depozitari si retrageri fiat: ',
    l_fiat_locked: 'blocat',
    l_fiat_money: '/luna',
  },
  landing_inputs: {
    email_placeholder: 'Introdu emailul',
    demo: 'Tranzacționează acum',
  },
  status_online_page: {
    status_online: 'Stare Online',
    table: {
      coin: 'Moneda',
      trading: 'Tranzacționare',
      deposits: 'Deposite',
      withdrawals: 'Retrageri',
      pending: 'Confirmare în procesare',
      last_trade: 'Ultima tranzacție cu succes',
      avg_time: 'Media timpului de procesare',
      online: 'Online',
      offline: 'Offline',
      d: 'd.',
      hr: 'hr.',
      min: 'min.',
      sec: 'sec.',
    },
  },
  trade_fees: {
    trade_fees_info: 'Informații despre comisioanele tranzacțiilor',
    trade_fees_info_cut: 'Trading fees',
    table: {
      pair: 'Pereche',
      market: 'Piață',
      limit: 'Limită',
    },
  },
  staking: {
    suc_change: 'Acumulare activata cu succes',
    profit: 'Incaseaza profit cu succes',
    staking_alert: 'Este necesar sa introduceti suma in campul de staking',
    error_staking: {
      balance: 'Nu există suficient sold disponibil',
      zero_input: 'Câmpul suma staking este obligatoriu',
      start_staking: 'Staking cu succes',
      stop_staking: 'Nu mai investi cu succes',
    },
    staking_plans: {
      daily: 'Zilnic',
      weekly: 'Saptamanal',
      monthly: 'Lunar',
      start_staking: 'Începe Staking',
      active_staking: 'Revendica Recompensa',
    },
    modals: {
      accrued_reward_modal: {
        confirm_disabling: 'Confirma dezactivarea',
        confirm_enabling: 'CONFIRM ACTIVAREA',
        accrued_reward: 'RECOMPENSA ACUMULATE',
        confirm: 'Confirmă',
        cancel: 'Anulare',
      },
      confirm_staking_modal: {
        confirm_staking: 'Confirma Staking?',
        coin_name: 'Nume Moneda',
        staking_amount: 'Cantitate Staking',
        period: 'Perioadă',
        estimated_annual_yield: 'Câștig anual estimat',
        accrued_reward: 'Recompensa Acumulata',
        cancel: 'Anulare',
      },
      redeem_reward_modal: {
        redeem_reward: 'REVENDICA RECOMPENSA',
        confirm_reward: 'CONFIRMA REVENDICAREA RECOMPENSEI ?',
        redeemable_amount: 'Suma care poate fi revendicata:',
        yes: 'Da',
        no: 'Nu',
      },
      star_staking_modal: {
        start_staking: 'INCEPE STAKING',
        enter_staking: 'Introduceti suma de staking pentru',
        total_amount: 'Suma totala disponibila pentru staking:',
        accrued_yield: 'Randament acumulat:',
        staking: 'Incepe Staking',
        buy: 'Cumpara',
        deposit: 'Depoziteaza',
      },
      stop_staking_modal: {
        stop: 'Stop',
        stop_current_staking:
          'Sunteti siguri ca doriti sa opriti planul curent de staking?',
        balance_locked:
          'De indata ce planul de staking va fi oprit suma totala blocata in staking impreuna cu recompensele castigate vor fi creditate in balanta personala de pe platfroma Coinzix.',
        stop_plan: 'Opreste planul curent de Staking',
        cancel: 'Anulare',
      },
    },
    tabs: {
      history_tab: {
        date: 'Data',
        event: 'Eveniment',
        plan_ID: 'Plan/ID',
        reward_change: 'Schimbare Recompensa ',
        plan_before: 'Suma planului inainte',
        plan_after: 'Suma planului dupa',
        balance_change: 'Schimbari Balanta disponibila',
        balance_before: 'Balanta Disponibila Inainte',
        balance_after: 'Balanta Disponibila Dupa',
        not_modifiend: 'Nemodificat',
        no_data: 'Nu există date',
      },
      my_active_plans_tab: {
        asset: 'Activ',
        annual_yield: 'Randament anual estimat',
        period: 'Perioada',
        amount: 'cantitate',
        generated_reward: 'Recompensa generata',
        accrued_reward: 'Recompensa Acumulata',
        daily: 'Zilnic',
        monthly: 'Lunar',
        redeem_reward: 'Revendica Recompensa',
        stop: 'Stop',
        no_data: 'Nu există date',
      },
      staking_plans_tab: {
        asset: 'Activ',
        annual_yield: 'Randament anual estimat',
        period: 'Perioada',
        min_amount: 'Valoare minimă',
        daily: 'Zilnic',
        monthly: 'Lunar',
        weekly: 'Saptamanal',
        start_staking: 'Incepe Staking',
        no_data: 'Nu există date',
      },
    },
    staking: {
      plans: 'Planuri Staking',
      rewards: 'Primești recompensă pentru depozit de monede și tokeni',
      staking_plans: 'Planuri Staking',
      my_active: 'Planurile Mele Active',
      my_history: 'Istoricul planurilor de staking',
    },
    event: {
      invest: 'Transfera catre staking',
      payment: 'Plata',
      take_profit: 'Incaseaza profit',
      closed: 'Inchis',
    },
  },
  staking_old: {
    minting_rewards: {
      my_rewards: {
        previous_rewards: 'Recompense anterioare',
      },
    },
  },
  coins_fees: {
    with_and_dep_fees: 'Comisioane Retrageri  si Depuneri',
    table: {
      coin: 'Monedă',
      refill_commissions: 'Comision depunere',
      withdraw_commissions: 'Comision retragere',
      coin_type: 'Tipul Monedei',
      percent: 'Procent',
      fixed: 'Fix',
      minimal: 'Minim',
      free: 'GRATUIT',
    },
    formula_text:
      'Comisionul este calculat dupa urmatoarea formula: Comision= Procentul din valoarea retragerii + Comision fix ; Daca comisionul este mai mic decat minimul se va aplica comisionul fix',
  },
  cur_tokens: {
    title: 'Valute & Tokeni',
    table: {
      coin: 'Moneda',
      token_type: 'Tip',
      rate: 'Curs',
      market_cap: 'Capitalizare de piata',
      change_24: 'Schimbare 24/h',
      volume_24: 'Volum 24/h',
      n_a: 'N/A',
    },
  },
  free_coins: {
    title: 'MONEDE BONUS',
    special_offer: 'Limitele zilnice s-au dublat.',
    special_wishes: 'Craciun fericit si un An Nou Fericit!',
    project_faucets:
      'Avem ceva ce știm că v-ar plăcea. Colectați acum criptomonedele dvs. gratuite și deveniți membru al clubului exclusivist Utilizatori Fideli Coinzix. Găsiți mai multe detalii mai jos pe pagina. Rămâneți la curent pe canalele noastre de socializare pentru cele mai recente știri.',
    click_get: 'COLECTAȚI MONEDELE GRATUITE de mai jos:',
    history: 'Istoric',
    rules: {
      title: 'Info',
      general_description: {
        title: 'Clubul Utilizatorilor Loiali Coinzix',
        desc_1:
          'O listă cu diferite monede oferite gratuit membrilor noștri Coinzix.',
        desc_2:
          'Monedele sunt actualizate în mod regulat în funcție de preferințele dumneavoastră.',
        desc_3:
          'Fiecare criptomonedă are o limită pe sesiune, marcată în tabelul de mai sus.',
        desc_4:
          'Fiecare sesiune are o durată predefinită de timp in care puteti primi numărul specificat de monede, marcată de asemenea în tabelul de mai sus.',
        desc_5: 'Monedele bonus sunt oferite o singură dată pe sesiune.',
      },
      how_it_works: {
        title:
          'Cum să colectați monedele gratuite oferite utilizatorilor loiali Coinzix?',
        desc_1:
          'Conectați-vă sau înregistrați-vă pe platforma Coinzix Exchange accesand pagina noastră ',
        desc_1_link: 'de înscriere.',
        desc_2:
          'Selectați din tabelul de mai sus moneda pe care doriți să o primiți gratuit, apăsând pe butonul <Obtineti>.',
        desc_2_a:
          '<Notă:> Dacă butonul <Obtineti> nu este activ, fie volumul zilnic al monedei a fost deja partajat utilizatorilor noștri fideli, fie ați primit deja suma disponibilă , dar sesiunile nu au expirat încă.',
        desc_2_b:
          '<Sfat:> Verificați din nou moneda în câteva ore sau după ce „Timpul rămas” s-a actualizat, pentru a debloca noul bonus de fidelitate.',
        desc_2_c:
          '<În curând:> Şi noi vă suntem loiali! Lucrăm din greu pentru a lansa o funcționalitate care vă va trimite actualizări automate atunci când o monedă gratuită este din nou disponibilă pentru colectare.',
        desc_3:
          'Apăsaţi butonul <„Obțineți”> pentru a colecta monedele gratuite selectate.',
        desc_3_a:
          '<Notă:> Se va deschide o fereastră separată cu instrucțiuni despre cum să le spuneți prietenilor de pe rețelele sociale despre bonusul dvs. de fidelitate. Postează linkul pe rețelele de socializare și distribuie-l prietenilor tăi. ',
        desc_3_b:
          '<Important:> După postarea ta, copiază linkul din publicație în casetă, astfel încât moderatorii noștri să-l poată verifica. Monedele vor fi trimise în portofel după ce echipa noastră validează postarea.',
        desc_3_c:
          '<Important:> Nu ștergeți postarea după ce primiți monedele în portofel, altfel veți fi scoşi din programul de fidelitate.',
        desc_4:
          'Monedele sunt ale dumneavoastra acum. Va urăm tranzacționare cu succes pe platforma noastră!',
      },
      summary: {
        desc_1:
          'Apreciem utilizatorii noștri fideli și ne pasă foarte mult de comunitatea noastră uimitoare!',
        desc_2:
          'Bucurați-vă de timpul petrecut pe platforma noastră, cunoașteți comunitatea și, drept mulțumire din partea noastră, colectați monedele gratuite cu doar câteva clicuri.',
        desc_3:
          'Facem cripto-ul ușor și accesibil pentru toată lumea, așa că veniți și vizitați canalele noastre comunitare pentru mai multe știri și oportunități!',
      },
    },
    table: {
      coin: 'Moneda',
      socials: 'Retele de socializare',
      payout_per_user: 'Plata pe utilizator',
      time_interval: 'Interval',
      daily_limit: 'Volum zilnic monede',
      time_left: 'Timp ramas',
      date_time: 'Timp',
      nickname: 'Utilizator',
      sum: 'Cantitate',
      payout: 'Plata',
      limit: 'limita',
    },
    modal: {
      title: 'Obtine monede',
      to_get:
        'Pentru a obtine monede gratuite distribuie aceasta postare despre {project} schimba',
      please_insert: 'Te rugam sa introduci linkul unde sa il putem verifica',
      confirm_captcha: 'Te rugam sa confirmi captcha',
    },
    reject_modal: {
      top_lvl: 'Monedele gratis sunt temporar blocate',
      second_lvl: 'si vor fi disponibile prin',
    },
  },
  voting: {
    title: 'Vot monezi',
    round: 'Routund',
    each_participant:
      'Fiecare participant poate selecta candidații pentru care ar dori să voteze mai jos. Fiecare utilizator înregistrat ar putea vota pentru mai mult de 1 candidat și ar putea vota integral doar o singură dată. Nu este necesară nicio taxă.',
    min_number: 'Numărul minim de voturi pentru runda curentă este',
    next_round_starts_at: 'Runda următoare începe în',
    day: 'ziua',
    of: 'din',
    starts_in: 'începe în',
    stats_is_hidden:
      'Unele informații statistice sunt ascunse. Pentru a le arăta toate',
    voting: 'Votare',
    history: 'Iistoric',
    information: 'Informații',
    voting_time: 'Ora votului',
    from: 'din',
    to: 'spre',
    all_members: 'Toții menbri cu o',
    account_are_eligible: 'contul este eligibili pentru a participa la vot',
    each: 'Fiecare',
    user_can_vote: 'utilizatorul poate vota pentru câți candidați îi place.',
    there_is_no_fee: 'Nu există comisioane la votare.',
    please_note: 'Nu uita',
    will_review:
      'va revizui numărul final de voturi obținut de fiecare candidat la sfârșitul perioadei de votare.',
    reserves_the_right:
      'își rezervă dreptul de a ajusta modul în care atribuie valoare fiecărui vot.',
    upon_completion:
      'La finalizarea procesului de vot și de asemenea la selectarea unei noi monede pentru listare,',
    will_list_the_coin:
      'va enumera moneda de pe bursa noastră într-un interval de timp rezonabil. Pe baza răspunsului pieței și a activității de tranzacționare, vom încerca să organizăm acest eveniment lunar.',
    project_reserves_all_rights:
      'își rezervă toate drepturile de a schimba regulile evenimentului de vot fără notificare prealabilă în orice moment, inclusiv revocarea rezultatelor sau descalificarea candidaților despre care se confirmă că s-au angajat în manipularea votului. Aceasta include, dar nu se limitează la nici o formă de stimulente financiare sau monetare, airdrops sau recompense oferite de concurență care vor influența voturile utilizatorilor. Ponderea fiecărui vot ar putea varia, de asemenea, în funcție de o listă de factori, inclusiv, dar fără a se limita la nivelul activității istorice a contului utilizat la vot și a altor factori suplimentari pe care îi considerăm importanți.',
    all_past_voting_completed:
      'Toate rundele de vot din trecut sunt finalizate',
    dont_miss: 'Nu rata rundele următoare, urmează',
    number_of_rounds: 'Numărul de runde',
    status: 'Stare',
    completed: 'Completă',
    winners: 'Câștigători',
    to_the_voting_page: 'Spre pagina de votare',
    coin_community_voting_results: 'Rezultatele votului de monede comunitar',
    voting_results: 'Rezultatele Votului',
    results: 'rezultate',
    per_round_capitalize: 'Per runda',
    total_capitalize: 'Total',
    table: {
      no: 'Nr.',
      coin: 'Moneda',
      name: 'Nume',
      number: 'Număr',
      of_votes: 'de voturi',
      proportion: 'Proporție',
      per_round_caps: 'PER RUNDĂ',
      total: 'TOTAL',
      team: 'ECHIPĂ',
      whitepaper: 'Whitepaper',
      social: 'Social',
    },
  },
  downloads: {
    keep_in_touch:
      'Păstrează legătura în timp ce faci oferte și în plus primiți notificări instantanee',
    download_suitable_version:
      'Descarcă versiunea potrivită pentru telefonul tău și înregistreaz-te pe site.',
    smart_functional: 'Funcționalități Smart',
    trading: 'Tranzacții',
    exchange_trading: 'Tranzacționare, reglementarea ordinelor și pozițiilor',
    wallets: 'Portofele',
    transactions_between:
      'Tranzacții între portofele și verificarea celor mai recente modificări ale contului',
    login: 'Autentificare',
    secured_api: 'Acces securizat la cheile API și securitate PIN / parolă',
    settings: 'Setări',
    graphic_interface: 'Configurare interfața grafica',
    notifications: 'Notificare',
    notifications_about:
      'Notificări despre orice tranzacții sau prețuri efectuate',
    popup: {
      trade_with: 'Tranzacționează cu ',
      mobile_app: 'aplicația mobilă',
      get: 'Descarcă',
    },
  },
  trading: {
    cross: 'Încrucișat',
    loss: 'Rata pierderilor',
    profit: 'Rata profitului,',
    buy: 'Cumpără',
    sell: 'Vinde',
    total: 'Total',
    price: 'Preț',
    amount: 'Cantitate',
    sum: 'Sumă',
    quantity: 'Cantitate',
    available: 'Disponibil',
    available_short: 'Dsbl',
    open: 'Deschis',
    order: 'comandă',
    orders: 'comenzi',
    history: 'istoric',
    date: 'data',
    limit_order: 'Comandă limită',
    limit: 'Limită',
    market: 'Piață',
    instant: 'Instant',
    advanced: 'Avansat',
    instant_exchange: 'Schimbati instant',
    fast_easy: 'RAPID & UŞOR',
    balance_available: 'Sold Disponibil',
    instant_info: 'Vă rugăm să confirmați conversia în termen.',
    you_receive: 'Veți primi',
    you_pay: 'Veti plati',
    preview_conversion: 'Previzualizare Conversie',
    convert: 'Schimbati',
    please_new_quote: 'Oferta a expirat. Vă rugăm să solicitați o nouă ofertă.',
    new_quote: 'Ofertă Nouă',
    ins_balance: 'Sold insufficient',
    ins_balance_min: 'Suma minima este {amount}',
    ins_rate: 'In prezent, nu exista ordine de contrapartida',
    ins_balance_to_max: 'Maxim.',
    stop_limit: 'Limită-Oprire',
    open_orders: 'Comenzi deschise',
    order_history: 'Istoric comenzi',
    order_id: 'ID Comandă',
    limit_price: 'Preț limită',
    symbol: 'Simbol',
    type: 'Tip',
    trade_type: 'Tip Tranzaționare',
    volume_done: 'Volum realizat',
    rate: 'Curs',
    status: 'Stare',
    create_date: 'Data',
    sell_limit: 'Limită vânzare',
    fee: 'Comision',
    cancel: 'Anulează',
    more: 'Mai mult',
    market_trades: 'Piață de tranzacționare',
    time: 'Timp',
    high: 'Ridicat',
    low: 'Scăzut',
    market_price: 'Prețul pieței',
    stop: 'Stop',
    chart: 'Grafic',
    no_trades: 'Fără tranzactii',
    no_orders: 'Fără comenzi',
    order_processing: 'Comanda este trimisă în procesare',
    order_completed: 'Comandă finalizată',
    profit_loss_zero: 'Valoarea trebuie să fie mai mare decât 0',
    exchange_fee:
      'Comisioanele asociate cu folosirea schimbului instant sunt dinamice si variaza intre minim 0.5% si maxim 2.5% fiind calculate automat de sistem.',
    commission: 'Comision',
    ticker: {
      coin: 'Moneda',
      last_price: 'Ultimul preț',
      change: 'Schimbare',
      volume: 'Volum',
    },
    tooltip: {
      total:
        'Important: Această suma aproximativă este valoarea de la momentul calculului, pe baza prețurilor din lista de comenzi. Dacă prețul crește sau scade până când trimiteți comanda, este posibil ca suma finală pe care o vindeți sau cumpărați să fie diferită.',
    },
    error: {
      rate_diff:
        'Nu se poate plasa comanda. Soldul de vânzare este momentan indisponibil pentru suma corespunzătoare din cauza scăderii rapide a prețului. Încercați din nou reducând Totalul sau Suma.',
    },
  },
  orders: {
    type: {
      buy: 'Cumpără',
      sell: 'Vinde',
    },
    trade_type: {
      limit: 'Limită',
      market: 'Piață',
      stop_limit: 'Limită-Oprire',
      instant: 'Instant',
    },
    status: {
      public: 'Public',
      done: 'Executat',
      closed: 'Închis',
      in_process: 'În procesare',
      creating: 'Se creează',
    },
  },
  balance: {
    title: 'Balanta',
    est_value: 'Valoare Estimată',
    history: 'Istoric',
    order_history: 'Istoric Comenzi',
    hide_small: 'Ascunde balantele zero',
    all_history: 'Tot istoricul',
    deposit_history: 'Istoric Depozitare',
    withdraw_history: 'Istoric retrageri',
    history_order_history: 'Comenzi',
    go_to_exchange: 'Mergi la schimb',
    refill: 'Comision',
    table: {
      recent: 'Recent',
      time: 'Timp',
      coin: 'Monedă',
      type: 'Tip',
      status: 'Stare',
      available: 'Balanta',
      on_orders: 'La Comenzi',
      valuation: 'Evaluare',
      lock_position: 'Blochează Poziția',
      action: 'Acțiune',
      all: 'Toate',
      deposit: 'Depozit',
      withdraw: 'Retragere',
      cancel: 'Anulează',
      details: 'Detalii',
      address: 'Adresă',
      IBAN: 'IBAN',
      bank_name: 'Nume banca',
      bank_address: 'Adresa banca',
      payment_comment: 'Cometariu',
      client_name: 'Client name',
      fee: 'Comision',
      memo: 'MEMO (TAG)',
      twofa_approve: 'Aproba 2FA',
      captcha_approve: 'Captcha',
      email_confirmation: 'Confirmare Adresa Email',
      processing_time: 'Timp de procesare',
      id: 'Id',
      payment: 'Plată',
      dispatch_volume: 'Volum de expediere',
    },
    deposit: {
      contractAddress:
        'Numele token-ului este {ISO_NAME} ({Full_Name}). Asigură-te că depui tokeni {ISO_NAME} ({Full_Name}) sub adresa contractului care se termină cu {contractAddressEnd}.',
      deposit_address: 'Adresă Depozitare',
      copy: 'Copiază',
      qr_code: 'Cod QR',
      view: 'Vizualizare',
      deposit_history: 'Istoric Depozitare',
      to_track: 'să urmărești comanda',
      cashier: 'Casier',
      tips: {
        title: 'Sfaturi',
        please_dont:
          'Asigură-te că nu depui alte monede digitale, cu excepția {depositCoin} la adresa de mai sus.',
        minimum_deposit:
          'Suma minimă a depozitului: {minRefillAmount} {depositCoin}. Orice depozit mai mic decât minimul nu vor fi creditate sau rambursate.',
        refill_comission_deposit: 'Comision de reumplere:',
        refill_comission_deposit_free: 'Liber',
        depositing_to_above:
          'Depunerea la adresa de mai sus necesită confirmări ale întregii rețele. Aceasta va fi realizata după {confirmationsCount} confirmări.',
      },
      attention:
        'Avertizare! Alege tipul de token {iso} înainte de a efectua o depunere.',
      simpleAttention: 'Avertizare! Tipul token-ului {iso} este:',
      token_type: 'Tip Token',
    },
    withdraw: {
      address: 'Adresă',
      amount: 'Cantitate',
      available: 'Balanta',
      min: 'Min',
      limit: 'Limiă',
      fee: 'Comision',
      dispatch_volume: 'Volum de expediere',
      receive_amount: 'Primești suma',
      fee_from_amount: 'Comision din sumă',
      request_withdraw: 'Cerere de retragere',
      range: 'Interval',
      confirmations: 'Confirmări',
      tips: {
        title: 'Sfaturi',
        to_ensure:
          'Pentru a asigura siguranța fondurilor tale, solicitarea ta de retragere va fi revizuită manual dacă strategia de securitate sau parola ta sunt modificate. Te rugăm să te astepti la orice apeluri telefonice sau e-mailuri de la personalul nostru.',
        please_make_sure:
          'Te rugăm să te asiguri că, computerul și browserul tău. sunt securizate și că informațiile tale sunt protejate împotriva manipulării sau scurgerii.',
      },
    },
    crypto_statuses: {
      created: 'Creat',
      sent: 'trimis',
      wait: 'Așteptare',
      moderation: 'Moderare',
      in_processing: 'În procesare',
      wait_confirmations: 'Confirmări așteptare',
      deleted: 'Șters',
      canceled: 'Anulat',
      emailed: 'Activat',
      waiting_2fa_approve: 'Se așteaptă aprobarea 2fa',
      waiting: 'Așteptare',
    },
    fiat_statuses: {
      created: 'Creat',
      wait_pay: 'Asteapta plata',
      deleted: 'Sters',
      canceled: 'Anulat',
      emailed: 'Email trimis',
      done: 'Realizat',
      waiting_2fa_approve: 'Se așteaptă aprobarea 2fa',
      moderation: 'Moderare',
      in_process: 'In progres',
      pending: 'In asteptare',
      wait_check: 'Verificarea datelor utilizatorului',
    },
    crypto_types: {
      refill: 'Reumplere',
      withdraw: 'Retragere',
    },
  },
  submit_request: {
    title: 'Formular de contact și asistență',
    here_to_help: 'Sunt aici pentru ajutor',
    title_head: 'Support',
    title_form: 'Support Form',
    type_message:
      'Testează și descrie problema în detalii pentru un răspuns mai bun și mai rapid.',
    our_team_will_reply:
      'Echipa noastră de asistență va răspunde în termen de aproximativ 24 de ore.',
    your_email: 'Email-ul tău',
    choose_theme: 'Alege tema',
    enter_message: 'Introdu mesajul tău',
    themes: {
      account: 'Cont',
      deposit: 'Depozitare',
      security: 'Securitate',
      trading_common: 'Tranzacționare',
      withdraw: 'Retragere',
      other: 'Altele',
    },
  },
  ieo: {
    title: '{data} Launchpad',
    descr: 'Platforma de lansare a monedelor',
    apply_btn: 'Aplica pentru lansare',
    buy_coin_btn: 'Cumpara moneda',
    round: 'Runda',
    tokens_amount: 'Cantitate Tokeni',
    available_curr: 'Valute disponibile',
    air_drop: 'Air Drop',
    start_time: 'Lansare',
    end_time: 'Incheiere',
    minBuy: 'Suma minima de cumparare',
    price: 'Pret Token',
    totalSell: 'Total Tokeni Vanduti',
    myTokens: 'Tokenii mei',
    web_site: 'Website',
    balance: 'Balance',
    error: {
      no_rate: 'Nu exista o evaluare pentru aceasta valuta',
      max_amount: 'Suma maxima este',
    },
    filter: {
      all: 'Toate proiectele',
      active: 'Proiecte active',
      success: 'Proiecte incheiate cu succes',
      upcoming: 'Proiecte in viitor',
    },
    info_statuses: {
      active: 'Active',
      upcoming: 'Proiecte in viitor',
      success: 'Succes',
    },
    detail: {
      toPrepare: 'PENTRU A PARTICIPA IN LAUNCHPAD',
      pleaseVerify: 'Va rugam sa va conectati la cont',
      verify: 'Autentificare',
      totalFunds: 'Fonduri stranse in total',
      timeLeft: 'Timp ramas',
      about: 'Despre Proiect',
      doc: 'Documentatie',
      tokenName: 'Denumire token',
      tokenPrice: 'Pret Token',
      tokenType: 'Tipul Tokenului',
      minPurchase: 'Cantitate minima de cumparare',
      distribution: 'Distributie tokeni',
      timeCreate: 'Data crearii',
      tokenAmount: 'Cantitate tokeni',
      bonus: 'Bonus',
      paymentCurr: 'Valuta acceptata',
      status: 'Status',
      token_sale: 'Vanzare token si economie',
      token_supply: 'Cantitate disponibila in total',
      token_distribution: 'Distributia tokenului',
      soft_cap: 'Suma minima de finantare',
      hard_cap: 'Suma maxima de finantare',
      launchpad_allocation: 'Alocare launchpad',
    },
  },
  notification: {
    error: {
      already_logged: 'Ai fost deja autentificat',
      email_already_taken: 'Ne pare rău, acest e-mail a fost deja utilizat',
      username_already_taken:
        'Ne pare rău, acest nume de utilizator a fost deja utilizat',
      invalid_code: 'Ne pare rău, acest cod nu este valid',
      file_not_selected:
        'Câmpul de încărcare a fișierului este necesar de completat',
      file_size_error: 'Marimea fișierului depășește limita admisă',
      not_add_to_book: 'Adresa nu este adăugată în Agendă',
      incorrect_rate: 'Cursul nu poate fi mai mic de 0',
      incorrect_vol: 'Volumul nu poate fi mai mic de 0',
      incorrect_vol_then: 'Volumul nu poate fi mai mic de {data}',
      check_rate: 'Verifică dacă cursul este specificat',
      check_input:
        'Verifică să existe numere, puncte și valorile să fie între valori min-max',
      err_create_order: 'Ne pare rău, comanda nu poate fi creată',
      err_create_order_27: 'Drepturile la această acțiune sunt limitate',
      some_err: 'Eroare neașteptată',
      withdraw_not_create: 'Solicitarea de retragere nu poate fi creată',
      withdraw_address: 'Adresa trebuie sa contina minim 3 caractere',
      not_enough: 'Nu există suficient sold disponibil',
      not_enough_on_balance: 'Nu există suficient sold disponibil ',
      not_enough_on_balance_iso: 'Nu există suficient sold disponibil {data}',
      check_inputs:
        'Verifică să existe numere, puncte și valorile să fie între valori min-max',
      no_address: 'Nicio adresă de afișat',
      no_payment_system: 'Niciun sistem de plată',
      not_get_email: 'Nu îți putem primi e-mailul, te rugăm să îl introduci',
      unknown_error: 'A apărut o eroare',
      username_in_pass: 'Parola nu poate conține numele de utilizator',
      verify_docs_file_format:
        'Acest format de fișier nu este acceptat. Folosiți unul dintre acestea: pdf, jpeg, png, jpg',
      withdraw_sum_and_comm_amount:
        'Suma de retragere și comisionul trebuie să fie mai mari decât suma minimă de retragere',
      withdraw_min_value: 'Valoarea minimă este',
      withdraw_max_value: 'Suma nu poate fi mai mare de',
      no_server_response:
        'Niciun răspuns de la server, încearcă din nou mai târziu',
      bad_server_response: 'Nu există conexiune la server',
      error_sending_pin_code: 'Eroare la trimiterea codului PIN',
      limit_receiving:
        'Limita de primire a codului PIN a fost depășită. Te rugăm să aștepți până la 10 secunde pentru a retrimite',
      limit_receiving_activation:
        'Limita pentru primirea mailului de activare a fost atinsa.Te rugam sa astepti pana la 2 minute pentru a retrimite din nou',
      error_sending: 'Eroare la trimiterea codului PIN prin e-mail',
      username_or_email: 'Introdu alt nume de utilizator sau email',
      url: 'Linkul nu este valid',
      account_not_active: 'Contul nu este activ',
      attempt_exceeded: 'Limita de încercări a fost depășită',
      login_cred_error: 'E-mailul sau parola sunt incorecte',
      withdraw_zero_amount: 'Cantitatea trebuie să fie mai mare de 0',
      withdraw_verif_error: 'Depășirea limitelor de retragere criptografice',
      refill_verif_error:
        'Procesul de verificare este necesar pentru a putea depune',
      withdraw_create_error: 'Cererea de retragere nu este creată',
      withdraw_whitelist_error: 'Retragere suspendata',
      no_recieve_amount:
        'Valoarea retragerii trebuie să depășească valoarea comisionului',
      something_went_wrong: 'Ceva n-a mers bine',
      upload_file_limit:
        'Imposibil de încărcat fișierul. Limita maximă a fost atinsă',
      withdraw_incorect_count_per_day:
        'Valoarea retragerii este mai mare decat limita maxima admisa pe zi',
      withdraw_max_user_limit_error: 'Suma maxima a fost depasita',
      amount_greater_than: 'Suma trebuie să fie mai mare decât',
      verification_required: 'Verificarea contului este obligatorie',
    },
    info: {
      amount: 'Suma',
      iban: 'IBAN Beneficiar',
      bank_add: 'Adresa Bancii',
      bank_name: 'Numele Bancii',
      client_name: 'Nume Beneficiar',
      payment_com: 'Detaliu de plata',
      acc_captcha_not_active:
        'Pentru a autoriza pe platformă, accesează verificarea captcha',
      acc_not_activated:
        'Pentru a te autentifica pe site, urmează linkul din e-mail',
      approximately_amount:
        'Această sumă este aproximativă și este utilizată numai în scop informativ.',
      old_pass_incorrect: 'Parola veche este incorectă',
      incorrect_captcha: 'Codul de la captcha este incorect',
      code_incorrect: 'Codul este incorect',
      fiat_unavailable: 'Crearea comenzii este temporar indisponibilă',
      fiat_warning:
        'Atentie! Cand faceti plata catre aplicatie va rugam sa va asigurati ca ati introdus codul de referinta in detaliile platii. Acest cod nu trebuie sa contina altceva decat cifrele mentionate mai sus.',
      fiat_big_amount:
        'Nu poți retrage această sumă acum, încearcă din nou mai târziu',
      expired_link: 'Ne pare rău, acest link nu mai este valid',
      not_foundes: 'PAGINA NU A PUTUT FI GĂSITĂ',
      back_home: 'Mergi înapoi la homepage',
      canceled_withdrawal: 'Retragerea este anulată',
      no_address: 'Ne pare rău, nu ai o adresă de reumplere',
      no_image: 'Ne pare rău, nu există nicio imagine disponibilă',
      email_not_found: 'Utilizatorul cu acest e-mail nu este găsit',
      unable_to_create_refill: 'Reumplerea este temporar indisponibilă',
      internal_err: 'Eroare internă',
      minimal_pair_amount:
        'Nu se poate crea comanda. Suma este mai mică decât cea minimă acceptata pentru această pereche',
      not_support_chars: 'Nu acceptăm următoarele caractere: ',
      ver_fio_step_required:
        'Vă rugăm să setați numele dvs. pentru a ajunge la pasul următor',
      no_documents_uploaded: 'Nu s-au încărcat documentele',
      document_is_not_uploaded: 'Documentul nu este încărcat',
      username_not_set:
        'Te rugăm să alegi mai întâi datele de autentificare ale proprietarului contului',
      website_address_not_valid: 'adresa site-ului nu este o adresă validă',
      disable_security_auth:
        'Autorizarea cu 2 factori este deja activată. Dezactivează-l mai întâi pe cel curent',
      security_auth_code_req_block: 'Codul secret este deja trimis',
      no_orders_in_book: 'Nu există comenzi din care să iei comisionul acum',
      need_login_first: 'Te rugăm să te autentifici mai întâi.',
      not_validation_file: 'Fișier invalid',
      not_save_file: 'Fișierul nu a fost încărcat',
      file_was_not_uploaded: 'document nevalid',
      error_else: 'Eroare de server necunoscută',
      reguired_2fa_antiphising:
        'Pentru a crea și a modifica codul anti-phishing, trebuie să activezi 2FA.',
    },
    success: {
      account_activated: 'Contul a fost activat',
      account_type_set: 'Tipul de cont setat cu succes',
      account_type_reset: 'Resetare tip cont',
      data_sent: 'Date trimise cu succes către server',
      data_is_copied: 'Datele au fost copiate cu succes în buffer',
      fiat_on_moderation: 'Plata confirmată',
      fiat_refill_canceled: 'Reumplerea este anulată',
      success_login: 'Autentificare cu succes',
      change_pass: 'Parola a fost schimbată cu succes',
      add_to_book: 'Adresă adăugată în Agendă',
      processing_order: 'Comanda este trimisă pentru procesare!',
      order_delete: 'Comandă stesă',
      document_deleted: 'Document șters',
      withdraw_create: 'Cererea de retragere a fost creată, confirmați vă rog',
      fiat_refill_create: 'Cerere de reumplere creată, așteaptă confirmarea',
      request_create: 'Cerere creată',
      code_confirm: 'Codul confirmat continuă în continuare',
      acc_sec_code_sent_mail:
        'Cod secret trimis pe e-mail, te rugăm să verifici',
      acc_sec_code_sent_google:
        'Cod secret trimis aplicației tale google, te rugăm să verifici',
      recovery_send:
        'Link-ul de recuperare a fost trimis la adresa ta de e-mail',
      recovery_send_forgot:
        'Daca exista un cont asociat cu acest e-mail, va vom trimite instructiuni pentru resetarea parolei in cateva momente',
      success_registration: 'Înregistrare Completă',
      registration_activation_need:
        'Link-ul cu activarea contului a fost trimis pe adresa ta de e-mail',
      send_mess: 'Mesaul tău este trimis',
      news_subscription:
        'Ai fost abonat cu succes la newsletter, promoții și anunțuri prin e-mail',
      news_un_subscription:
        'Ai fost dezabonat pentru știrile, promoțiile și anunțurile noastre',
      confirmation_sent_to_email:
        'Comanda creata cu succes. Linkul de confirmare a fost trimis pe email',
      upload_file_success: 'Document de verificare încărcat',
      delete_file_success: 'Document de verificare șters',
      antiphishing_installed: 'Codul anti-phishing a fost instalat cu succes',
    },
  },
  validation: {
    required_email: 'Câmpul "E-mail" este obligatoriu',
    enter_correct_email: 'Introdu un e-mail valid',
    required_password: 'Câmpul "Parolă" este obligatoriu',
    required_repeat_password: 'Câmpul "Repetă parola" este obligatoriu',
    incorrect_old_password: 'Parolă veche incorectă',
    password_format:
      'Câmpul "Parolă" trebuie să conțină cel puțin 6 caractere: majuscule (A-Z) minuscule (a-z), cifre (0-9)',
    anti_phishing_format:
      'Te rugăm să introduci 4-20 caractere non-speciale: majuscule (A-Z) minuscule (a-z), cifre (0-9)',
    repeat_password_not_valid: 'Câmpul "Repetă parola" nu este valid',
    you_have: 'Ai',
    tries_left: 'încercări rămase',
    try_left: 'încercare',
    attempt_limit:
      'Limita de încercări a fost depășită, încearcă din nou mai târziu',
    must_be_at_least: 'Câmpul trebuie să fie cel puțin',
    required_theme: 'Câmpul "Temă" este obligatoriu',
    required_message: 'Câmpul "Mesaj" este obligatoriu',
    field_is_required: 'Câmpul este obligatoriu',
    input_correct_social: 'Te rugăm să introduci un link social corect',
    code_field_required: 'Câmpul "Cod" este obligatoriu',
    amount_field_required: 'Câmpul "Cantitate" este obligatoriu',
    address_field_required: 'Câmpul "Adresă" este obligatoriu',
    address_is_invalid: 'Adresa nu este validă',
    currency_required: 'Câmpul "Currency" este obligatoriu',
    address_label_required: 'Câmpul "Adresă" este obligatoriu',
    wallet_address_required: 'Câmpul "Adresă Portofel" este obligatoriu',
    address_book_add: 'Adresa a fost adăugată cu succes în Agendă',
    address_book_deleted: 'Adresa a fost eliminată din Agendă',
  },
  footer: {
    about_us: 'Despre noi',
    about: 'Despre',
    terms_of_use: 'Termeni de Utilizare',
    privacy_policy: 'Politica de Confidențialitate',
    cookies_policy: 'Politica cookie-urilor',
    risk_and: 'Declarație privind divulgarea riscurilor',
    aml_kyc: 'Politica AML & KYC',
    security: 'Securitate',
    news: 'Știri',
    service: 'Servicii',
    curr_and_tokens: 'Monede și Tokeni',
    fees: 'Comisioane',
    referral: 'Fidelizare',
    mobile_app: 'Aplicație Mobilă',
    status_online: 'Stare Online',
    support: 'Suport',
    submit_request: 'Trimite o Cerere',
    api_documentation: 'Documentație API',
    apply_to_list: 'Aplică în listă',
    community: 'Comunitate',
    channel: 'canal',
    chat: 'discuție',
    all_rights: 'Toate drepturile rezervate',
    bug_bounty: 'Vânătoare de Bug-uri',
  },
  support_and_faq: 'Asistență și întrebări frecvente',
  about_coocies_modal: {
    main_text:
      'Site-ul nostru web folosește cookie-uri pentru a vă oferi servicii de cea mai înaltă calitate posibila, pentru a analiza traficul nostru și în scopuri de securitate și marketing. Vizitând site-ul nostru web, sunteți de acord cu politica noastră de cookie-uri.',
    link_text: 'Citește mai multe despre cookie-uri',
    accept: 'Accept',
  },

  two_fa_modal: {
    title: 'Verificare 2FA',
    enter_2fa_code: 'Introduceți codul 2FA aici',
    type_2fa_code: 'Introduceți aici {data} codul 2fa',
    code_is_sent: 'Introduceți codul de e-mail',
    code_is_sent_google: 'Introduceți codul Google Authenticator',
    two_fa_code_sent:
      'Codul de autentificare cu doi factori este trimis pe adresa ta de e-mail',
    google_2fa: {
      p_1: 'Primul pas este să descarci aplicația Google Authenticator pentru dispozitivul tău Android sau iOS. Dacă ai nevoie de ajutor pentru a începe, consultă pagina de asistență Google.',
      p_2: 'Dacă nu ai acces la Android Play Store sau App Store, există alte opțiuni pentru obținerea Google Authenticator: Android Download, Google Chrome Plugin sau iTunes App Store.',
      p_3: 'După ce primești codul, lipiți-l aici și trimite-l.',
      scan_qr: 'Scanează QR-code-ul',
      enter_token: 'Introdu token-ul mai jos',
      p_4: 'Token-ul nu va mai fi afișat din nou după ce 2FA este activat. Dacă ai mai multe dispozitive, adaugă token-ul contului tău într-un carnețel de notițe de siguranță înainte de a da clic pe activare. (Notă: TOken-ul contului tău se va schimba de fiecare dată când reîncarci browserul',
    },
    resend: 'Retrimiteți',
  },
  password_change_modal: {
    title: 'Schimba parola',
  },
  anti_phishing_modal: {
    title_create: 'Creează un cod anti-phishing',
    title_change: 'Schimbă codul anti-phishing',
    input_label: 'Codul Anti-phishing',
  },
  confirm_withdraw_modal: {
    title: 'Verificare standard de securitate',
    this_action_requires:
      'Această acțiune necesită o verificare de securitate suplimentară.',
    enter_code: 'Introdu codul pentru a continua',
    enter_number_placeholder: 'Introdu numărul de confirmare',
    confirmation_step: 'Pas de confirmare',
  },
  link_to_email_modal: {
    link_sent:
      'Linkul de confirmare de retragere a fost trimis pe adresa ta de e-mail. Te rugăm să îl urmezi pentru a confirma comanda de retragere.',
    go_to_withdraw_history: 'Accesează istoricul retragerilor',
    go_to_email: 'Mergi la email',
  },
  timer_modal: {
    unavailable: 'Retragerea va fi disponibilă prin',
    login_timer: 'Retragerea va fi disponibilă prin',
    password_timer: 'După schimbarea parolei, retragerea este blocată temporar',
    hours: 'ore',
    min: 'min',
    sek: 'sec',
  },
  qr_code_modal: {
    text: 'Scanați codul QR și obțineți un link de recomandare',
  },
  confirmation_messages: {
    please_await: 'Te rugăm să aștepți linkul de confirmare',
    withdrawal_confirmed: 'Retragerea a fost confirmată cu succes',
    withdrawal_canceled: 'Retragerea a fost anulată cu succes',
    refill_canceled: 'Depozitare anulata cu succes',
    code_not_valid: 'Ne pare rău, acest cod nu este valid',
    link_activated:
      'Linkul este acum activat cu succes. Acest pas va duce la retragerea comenzii la procesul de moderare. Dacă dorești să anulezi comanda, fă clic pe butonul Anulare sau apasă Confirmare pentru a continua',
  },
  games: {
    games: 'Games',
    low_balance: 'Not enough on balance',
  },
  futures: {
    buy: 'Buy/Long',
    sell: 'Sell/Short',
  },
  vip: {
    title: 'Nivelul comisionului de tranzactionare',
    highest_level: 'Nivelul tau Vip este cel mai inalt',
    to_upgrade_to: 'Pentru a trece la nivelul',
    trade_another: 'mai tranzactionati',
    trade_market: 'in piata de tranzactii spot',
    and: 'si',
    increase_balance: 'sa va mariti balanta {iso} cu ',
    limit: 'Limita',
    market: 'Piata',
    trade_turnover: 'Rulaj Tranzactii Spot',
    your_balance: 'Balanta {iso}',
    level: 'Nivel',
    trade__Turnover: 'Rulaj tranzactii',
    or: 'sau',
    balance: 'Balanta {iso}',
    you_will_need: 'trebuie sa',
    days_in: ' zile in',
    discount_text: 'Reducere {iso}',
    commission_toggle:
      'Permiteți plata taxelor de tranzacționare folosind {iso}',
    commission_notification_allow:
      'Permiteți plata taxelor de tranzacționare folosind {iso}',
    commission_notification_disallow:
      'Nu permiteți plata taxelor de tranzacționare folosind {iso}',
    discount_status_info:
      'PRIN ACTIVAREA DISCOUNTULUI {iso} VETI PLATI COMISIOANELE FOLSIND MONEDA {full_iso}',
    discount_status: 'Status discount {iso}',
    enabled: 'ACTIVAT',
    disabled: 'DEZACTIVAT',
    buy: 'Cumpara {iso}',
    baner_commission_exclamation: '!',
    baner_commission:
      'Economisiți {percent}% din comisioane folosind MONEDA {iso}',
    baner_commission_disabled: 'SALVEAZA {percent}% DIN COMISIOANE FOLOSIND',
    iso_coin_disabled: 'MONEDA {iso}',
  },
  qrCodeCamera: {
    not_allowed_error: 'EROARE: Trebuie să permiți accesul la cameră',
    not_found_error: 'EROARE: Nu s-a găsit nici o cameră pe acest dispozitiv',
    not_supported_error:
      'EROARE: Din motive de securitate, este necesară o conexiune HTTPS sau localhost',
    not_readable_error: 'EROARE: Folosești camera într-o altă aplicație?',
    over_constrained_error: 'EROARE: Camerele instalate nu sunt compatibile',
    stream_api_not_supported_error:
      'EROARE: Stream API nu este compatibil cu acest browser',
    insecure_context_error:
      'EROARE: Accesul la camera este permis doar in cadrul unei conexiuni securizate. Foloseste HTTPS sau localhost în loc de HTTP',
    other_error: 'EROARE: A fost identificată o problemă la cameră ({error})',
  },
  recaptcha_badge: {
    text_start: 'Acest site este protejat de reCAPTCHA si de',
    text_policy: 'Politica de Confidentialitate',
    text_and: 'si',
    text_terms: 'Termenii de Utilizare',
    text_apply: 'Google',
  },
  email_confirmation_modal: {
    title: 'Cod Confirmare Retragere',
    description:
      'TCodul de confirmare pentru retragerea dumneavoastra a fost trimis prin email. Va rugam sa va verificati emailul si sa introduceti codul aici.',
  },
}